Blocking tree are saved in parquet file #82
zinggAI/zingg pull request #120
Opened 2022-01-08 21:47 UTC by navinrathore

"zingg.block" is a directory comprising parquet files. It was a file.
BlockingtreePipe, by default, has Overwrite mode. It should be OK in read().

2022-01-10 08:45 UTC, sonalgoyal commented on client/src/main/java/zingg/client/util/Util.java
> -
should there be some kind of buffering? bufferedoutputstream etc?

2022-01-10 08:45 UTC, sonalgoyal commented on core/src/main/java/zingg/util/BlockingTreeUtil.java
> +		Dataset<Row> df = spark.sqlContext().createDataFrame(rowRDD, schema).toDF();
shouldnt we coalesce the df before writing?

2022-01-10 08:45 UTC, sonalgoyal requested changes
please take a look at the comments

2022-01-10 21:30 UTC, navinrathore commented on client/src/main/java/zingg/client/util/Util.java
> -
There should not be any buffering, I feel. Buffering happens mainly for relatively expensive operations like disk I/O, network activity. Also, particular operation should be quite often.
Your opinion please?

2022-01-10 21:30 UTC, navinrathore commented on core/src/main/java/zingg/util/BlockingTreeUtil.java
> +		Dataset<Row> df = spark.sqlContext().createDataFrame(rowRDD, schema).toDF();
Added.

2022-01-11 04:49 UTC, sonalgoyal commented on client/src/main/java/zingg/client/util/Util.java
> -
buffering is pretty standard, dont see how it harms. please add.

2022-01-11 04:49 UTC, sonalgoyal requested changes
buffering

2022-01-11 09:37 UTC, navinrathore commented on client/src/main/java/zingg/client/util/Util.java
> -
Yes. Added. Hope it is the correct way and does the expected.

2022-01-11 11:07 UTC, merged