data and scripts for amazon-google dataset
zinggAI/zingg pull request #131
Opened 2022-01-14 13:09 UTC by navinrathore

2022-01-14 13:09 UTC, navinrathore commented
Run the pyspark scripts from dirctory - examples/amazon-google/scripts
 spark-submit prepareTestDataSpark.py
 
 training file has cluster_id and label at the end right now. trying to move them in the beginning...selection column list needs to be adjusted accordingly.

2022-01-14 13:19 UTC, sonalgoyal requested changes

2022-01-14 13:19 UTC, sonalgoyal commented on examples/amazon-google/config.json
> +{
why do we need two configs - dont we need just one for linking?

2022-01-14 13:19 UTC, sonalgoyal commented on examples/amazon-google/configWithTrainingSamples.json
> +		"modelId": 1101,
our model series is 100

2022-01-14 13:19 UTC, sonalgoyal commented on examples/amazon-google/configWithTrainingSamples.json
> +		"collectMetrics": false
this flag should be removed.

2022-01-14 13:19 UTC, sonalgoyal commented on examples/amazon-google/scripts/prepareTestDataSpark.py
> +tableA="../dataset_orig/tableA.csv"
rename script location folder to original

2022-01-14 13:19 UTC, sonalgoyal commented on examples/amazon-google/scripts/prepareTrainDataSpark.py
> +def readCSVFile(spark, fileName) :
why not have all the methods in one script and use them? Ideally these scripts should work for other datasets too.

2022-01-14 19:13 UTC, navinrathore commented on examples/amazon-google/config.json
> +{
Removed.
It was added if somebody wants to generate own training/labelled data.

2022-01-14 19:13 UTC, navinrathore commented on examples/amazon-google/scripts/prepareTestDataSpark.py
> +tableA="../dataset_orig/tableA.csv"
removed

2022-01-14 19:14 UTC, navinrathore commented on examples/amazon-google/scripts/prepareTrainDataSpark.py
> +def readCSVFile(spark, fileName) :
It will work for other datasets also.
They will be merged.

2022-01-15 16:08 UTC, sonalgoyal reviewed
what is the need for config.json?

2022-01-15 17:46 UTC, navinrathore commented
The code was updated yesterday with some changes. Some improvements were made and some mistakes were rectified.
Some analysis of the results was also done.
**Result**
Test1 (Google): Total 2293 records -> 771 unique  ==> After Linking 565 records found matched
Test2 (AWS)   : Total 2293 records -> 1090 unique  ==> 2287 records found matched
Observations:  in teset2 records (we did have matched records, we had other partially matched records). Perhaps updating model with some parameters, results can be improved. the score/probability was around 0.45 mostly.
Training data: both train,csv (6874 recs)and valid.csv(2293) was used to train the model.

2022-01-15 17:47 UTC, navinrathore commented on examples/amazon-google/scripts/prepareTestDataSpark.py
> +def init() :
It's outdated. already cleaned.

2022-01-15 17:47 UTC, navinrathore commented on examples/amazon-google/config.json
> +					"name": "test2",
ok

2022-01-15 17:47 UTC, navinrathore commented on examples/amazon-google/config.json
> +			"name": "test1",
ok

2022-01-15 17:47 UTC, navinrathore commented on examples/amazon-google/configWithTrainingSamples.json
> +		"collectMetrics": false
already done.

2022-01-15 17:55 UTC, navinrathore commented on examples/amazon-google/config.json
> +{
File removal will be part of next checkin. Version from first checkin is still there.

2022-01-16 03:24 UTC, navinrathore commented
### Some queries/notes about changes:
* field 'price' is 'exact'/double and all others are 'fuzzy'/string
* In configWithTrainingSample.json, the training sample data comprises both train.csv and valid.csv data
* **In configWithTrainingSample.json, is "data" attributes compulsory? it currently has both tableA and tableB. Or it could have data corresponding to train.csv and valid.csv**
*  **What could be ideal location of the script? Some minor changes can be made it absolutely generic in terms of location**
*  Same script works with all dataset without any change. 
* Naming is simple testA, TestB etc.

2022-01-16 03:25 UTC, navinrathore commented on examples/amazon-google/scripts/prepareTrainDataSpark.py
> +def readCSVFile(spark, fileName) :
There is only one script now

2022-01-16 03:27 UTC, navinrathore commented on examples/amazon-google/config.json
> +					"name": "test2",
Yes. I've made the changes. 
For other datasets, these fields may be updated accordingly.

2022-01-17 14:42 UTC, merged