Initial changes for Spark to Snowpark migration
zinggAI/zingg pull request #154
Opened 2022-02-27 03:35 UTC by navinrathore

Only limited files included

2022-02-27 03:46 UTC, sonalgoyal requested changes
thanks! please make the following changes
a. No generic * imports - change to specific class, package imports
b. SaveMode - get from Snowflake
c. Instead of commenting out spark stuff in imports, just edit 
d. Why are jdk versions bumped up to 11? Is that what snowflake needs? Our Spark stuff is on jdk8, makes sense to have the same version unless Snowpark is incompatible.
e. Why do we need scala collection classes in TrainingDataFinder? I dont see them used anywhere?

2022-02-28 11:49 UTC, navinrathore commented
Java 11 is only supported version.

2022-03-01 04:06 UTC, navinrathore commented
A few places the snowpark api requires Seq object. One way is do it in below mentioned way. There could be alternatives such as directly create scala Seq in the java class. 
// Util.java #470-473
List<Column> cols = new ArrayList<Column>();
cols.add(dupesActual.col(colName + "temp"));
cols.add(dupesActual.col(colName));		 
dupesActual = dupesActual.withColumn(colName,
        functions.concat(JavaConverters.asScalaIteratorConverter(cols.iterator()).asScala().toSeq()));

2022-03-01 05:47 UTC, sonalgoyal requested changes

2022-03-01 05:47 UTC, sonalgoyal commented on client/src/main/java/zingg/client/util/Util.java
> +				com.snowflake.snowpark.functions.lit(append));
why not let the preceding line work? The right import would fix it, no?

2022-03-01 05:47 UTC, sonalgoyal commented on client/src/main/java/zingg/client/util/Util.java
> +				functions.concat(JavaConverters.asScalaIteratorConverter(cols.iterator()).asScala().toSeq()));
indentation?

2022-03-01 05:47 UTC, sonalgoyal commented on client/src/main/java/zingg/client/util/Util.java
> +				functions.concat(JavaConverters.asScalaIteratorConverter(cols.iterator()).asScala().toSeq()));
the logic is looking off to me? maybe we can discuss this.

2022-03-01 05:47 UTC, sonalgoyal commented on core/src/main/java/zingg/TrainingDataFinder.java
> +						posPairs = posPairs.drop(new String[]{ColName.MATCH_FLAG_COL,
Lines 46 and 48 and 47 and 49 look same to me?

2022-03-01 05:47 UTC, sonalgoyal commented on core/src/main/java/zingg/TrainingDataFinder.java
> +				// posPairs = posPairs.cache();
why not cacheresult ?

2022-03-01 05:47 UTC, sonalgoyal commented on core/src/main/java/zingg/TrainingDataFinder.java
> +				//if (negPairs!= null) negPairs = negPairs.persist(StorageLevel.MEMORY_ONLY());
please use cacheResult

2022-03-01 05:47 UTC, sonalgoyal commented on core/src/main/java/zingg/TrainingDataFinder.java
> +		DataFrame dupes2 = dupes1.sort(dupes1.col(ColName.CLUSTER_COLUMN), null);
Is null necessary here?

2022-03-01 05:47 UTC, sonalgoyal commented on core/src/main/java/zingg/TrainingDataFinder.java
> +		pos = pos.sort(pos.col(ColName.SCORE_COL), null);
please check if you can call the method without null?

2022-03-01 05:47 UTC, sonalgoyal commented on core/src/main/java/zingg/TrainingDataFinder.java
> +		neg = neg.sort(com.snowflake.snowpark.functions.col(ColName.SCORE_COL), null);
why is an explicit com.snowflake...call needed here?

2022-03-01 05:47 UTC, sonalgoyal commented on core/src/main/java/zingg/TrainingDataFinder.java
> +		neg = neg.sort(com.snowflake.snowpark.functions.col(ColName.SCORE_COL), null);
also null?

2022-03-01 05:47 UTC, sonalgoyal commented on core/src/main/java/zingg/util/DSUtil.java
> +		DataFrame lines1 = getPrefixedColumnsDS(lines); //.cache();
cacheResult ?

2022-03-01 05:47 UTC, sonalgoyal commented on core/src/main/java/zingg/util/DSUtil.java
> +	 	dupes2 = dupes2.toDF(dupes1.schema().names()); //columns()).cache();
cahceResult

2022-03-01 05:47 UTC, sonalgoyal commented on core/src/main/java/zingg/util/DSUtil.java
> +			trFile = trFile.drop(ColName.PREDICTION_COL, null);
null - is it necessary?

2022-06-17 04:27 UTC, closed without merging