Data processing for Stop Words removal
zinggAI/zingg pull request #191
Opened 2022-03-30 07:11 UTC by navinrathore

2022-03-30 07:32 UTC, sonalgoyal requested changes

2022-03-30 07:32 UTC, sonalgoyal commented on core/src/main/java/zingg/util/DSUtil.java
> +				wordList = stopWords.toJavaRDD().map(new Function<Row, String>() {
do you need to convert to javardd here, cant we select the column _c0 and collect?

2022-03-30 07:32 UTC, sonalgoyal commented on core/src/main/java/zingg/util/DSUtil.java
> +	public static UserDefinedFunction removeStopWords(List<String> stopWords) {
move to new package. preprocess under core and have top level class

2022-03-30 07:32 UTC, sonalgoyal commented on core/src/main/java/zingg/util/DSUtil.java
> +	public static UserDefinedFunction removeStopWords(List<String> stopWords) {
please also write junit for this

2022-03-30 07:32 UTC, sonalgoyal commented on core/src/main/java/zingg/TrainingDataFinder.java
>  		dupesActual = DFUtil.addClusterRowNumber(dupesActual, spark);
refer what we discussed today. alignDupes should have the actual values - please use join. select only relevant z_columns from dupesActual, join with sampleOriginal and pass to alignDupes.

2022-03-31 03:12 UTC, navinrathore commented on core/src/main/java/zingg/util/DSUtil.java
> +				wordList = stopWords.toJavaRDD().map(new Function<Row, String>() {
List<string> is needed. select() and then collect() will give List<Row> or Array[ROW].
Still could it be simplified?

2022-03-31 03:12 UTC, navinrathore commented on core/src/main/java/zingg/TrainingDataFinder.java
>  		dupesActual = DFUtil.addClusterRowNumber(dupesActual, spark);
**before or after alignDupes.** How will the impact be different? after alignDupes, the work is simple and straightforward.

2022-03-31 03:14 UTC, navinrathore commented on core/src/main/java/zingg/util/DSUtil.java
> +	public static UserDefinedFunction removeStopWords(List<String> stopWords) {
New class **zingg.preprocess.StopWords** has been introduced. That's what expected?

2022-03-31 04:53 UTC, sonalgoyal commented on core/src/main/java/zingg/util/DSUtil.java
> +				wordList = stopWords.toJavaRDD().map(new Function<Row, String>() {
yes so why javardd - cant we do the same using dataset?

2022-03-31 04:53 UTC, sonalgoyal commented on core/src/main/java/zingg/util/DSUtil.java
> +	public static UserDefinedFunction removeStopWords(List<String> stopWords) {
junit

2022-03-31 06:05 UTC, sonalgoyal requested changes

2022-03-31 06:05 UTC, sonalgoyal commented on core/src/main/java/zingg/util/DSUtil.java
> +		Dataset<Row> modDS = ds;
just use ds as it is immutable anyways?

2022-03-31 06:05 UTC, sonalgoyal commented on core/src/main/java/zingg/TrainingDataFinder.java
>  		dupesActual = DFUtil.addClusterRowNumber(dupesActual, spark);
alignDupes is aligning the columns from the pairs. logically we should be working on the actual data here. also we can avoid the o_ approach which is more like a hack. let us do joins here. easier to understand

2022-03-31 06:05 UTC, sonalgoyal commented on core/src/main/java/zingg/util/DSUtil.java
> +	public static Dataset<Row> postprocessForStopWords(Dataset<Row> actual, Dataset<Row> orig, Arguments args) {
let us select the z_ columns and join with orig. Much easier to understand

2022-03-31 07:47 UTC, navinrathore commented on core/src/main/java/zingg/util/DSUtil.java
> +				wordList = stopWords.toJavaRDD().map(new Function<Row, String>() {
avoided javardd call

2022-03-31 07:48 UTC, navinrathore commented on core/src/main/java/zingg/util/DSUtil.java
> +	public static UserDefinedFunction removeStopWords(List<String> stopWords) {
junit shall be added once, prima facie, code looks fine.

2022-03-31 07:50 UTC, navinrathore commented on core/src/main/java/zingg/TrainingDataFinder.java
>  		dupesActual = DFUtil.addClusterRowNumber(dupesActual, spark);
o_ approach has been dropped. selection of appropriate columns and then joining with the original is used.
It works fine after alignDupes().

2022-03-31 07:51 UTC, navinrathore commented on core/src/main/java/zingg/TrainingDataFinder.java
> +		dupes2.show(8);
done

2022-03-31 07:51 UTC, navinrathore commented on core/src/main/java/zingg/util/DSUtil.java
> +		Dataset<Row> modDS = ds;
done

2022-03-31 07:51 UTC, navinrathore commented on core/src/main/java/zingg/util/DSUtil.java
> +	public static Dataset<Row> postprocessForStopWords(Dataset<Row> actual, Dataset<Row> orig, Arguments args) {
yes, that is only done. Important thing is at what step is done??

2022-03-31 08:22 UTC, sonalgoyal commented
please add respective junits so that we can close.

2022-04-03 08:58 UTC, navinrathore commented
New changes are: 
* For Linker, Original restoration changes.
* Fix for Documenter Junit
* Stop words specific Junit tests
* Stop Words documentation

2022-04-05 06:06 UTC, sonalgoyal requested changes

2022-04-06 03:29 UTC, navinrathore commented on core/src/main/java/zingg/preprocess/StopWords.java
> +				wordList = stopWords.select("_c0").collectAsList().stream().map(f -> f.getString(0)).collect(Collectors.toList());
Modified the code

2022-04-06 03:29 UTC, navinrathore commented on core/src/main/java/zingg/preprocess/StopWords.java
> +	}
Changed to pattern matching.

2022-04-06 03:29 UTC, navinrathore commented on core/src/main/java/zingg/preprocess/StopWords.java
> +    public static Dataset<Row> postprocess(Dataset<Row> actual, Dataset<Row> orig) {
Moved.

2022-04-06 03:30 UTC, navinrathore commented on core/src/main/java/zingg/preprocess/StopWords.java
> +
COL_ID is already part of alignDupes() but not alignLinked(). so it has been introduced in postprocessLinked(), but deleted after join() step. I think ID is the only join-able column. Isn't it?

2022-04-06 03:30 UTC, navinrathore commented on core/src/test/java/zingg/preprocess/TestStopWords.java
> +import zingg.client.Arguments;
Moved two methods.

2022-04-06 03:31 UTC, navinrathore commented on core/src/test/java/zingg/preprocess/TestStopWords.java
> +	public void testRemoveStopWords() {
Added @DisplayName, However, there could be an alternative @DisplayNameGeneraator based on the function name. Currently, only _ are replaced . CamelCase one is not there. but a extendable class is there that we can use. Or we can wait till future version
e.g. ifItIsDivisibleBy4ButNotBy100() -->>  if It Is Divisible By 4 But Not By 100

2022-04-06 03:33 UTC, navinrathore commented on core/src/test/java/zingg/preprocess/TestStopWords.java
> +
There are two test cases already that covers the same intention. However, more test cases would be written after discussion.
LowerCases testing of stop words and the text has been covered in test cases.

2022-04-06 03:34 UTC, navinrathore commented on core/src/test/java/zingg/preprocess/TestStopWords.java
> +	@Test
Added @DisplayName, However, there could be an alternative @DisplayNameGeneraator based on the function name. Currently, only _ are replaced . CamelCase one is not there. but a extendable class is there that we can use. Or we can wait till future version
e.g. ifItIsDivisibleBy4ButNotBy100() -->> if It Is Divisible By 4 But Not By 100

2022-04-06 03:36 UTC, navinrathore commented
Needless to say, the code need to be refactored when other preprocessing requirements are added. Similarly, Test cases should also be elaborated.

2022-04-19 07:49 UTC, navinrathore commented
In html template, set width of columns to auto (to fit content length), not to page width as earlier
In csv template, count of stopword has been added
StopWords.java, if cell is null, do nothing. It was an issue
Documentor.java, 
	a) blank html files for the z columns to have conssitency in generated html file for all columns
	b) moved the stopword html/csv directories verification and creation out of every call of findAndWriteStopWords.

2022-04-19 08:13 UTC, sonalgoyal reviewed
- test for Mobile/T-Mobile pattern
- stop words should have header - StopWord, Count
- read from StopWord column not _c0
- https://stackoverflow.com/questions/40038575/how-to-match-the-forward-slash-using-regex

2022-04-21 09:44 UTC, merged