Z columns doc to have different template.
zinggAI/zingg pull request #257
Opened 2022-05-13 04:17 UTC by navinrathore

Zingg internal columns (Z columns) should have different template.

2022-05-13 04:47 UTC, sonalgoyal requested changes

2022-05-13 04:47 UTC, sonalgoyal commented on core/src/main/java/zingg/documenter/ColumnDocumenter.java
> +		if (col.equals(ColName.CLUSTER_COLUMN)) {
This needs to go in the template, not in the java code

2022-05-13 04:47 UTC, sonalgoyal commented on core/src/main/java/zingg/documenter/ColumnDocumenter.java
>  	private final String CSV_TEMPLATE = "stopWordsCSV.ftlh";
One thing I seem to have missed in my earlier reviews - we should have column templates which include stop word templates. Then it much easier to keep stuff modular and extend etc as needed

2022-05-13 07:12 UTC, navinrathore commented on core/src/main/java/zingg/documenter/ColumnDocumenter.java
>  	private final String CSV_TEMPLATE = "stopWordsCSV.ftlh";
moved content in a separate template and included in the parent template

2022-05-13 07:12 UTC, navinrathore commented on core/src/main/java/zingg/documenter/ColumnDocumenter.java
> +		if (col.equals(ColName.CLUSTER_COLUMN)) {
Moved to Template in if else blocks.

2022-05-13 13:49 UTC, navinrathore commented
#256

2022-05-16 03:58 UTC, sonalgoyal requested changes
a. z col list should just be columns that star with z_
b. StopWordDocumenter should be introduced and included in the ColumnDocumenter. All code and logic for StopWords should go in there. We can then add more documenters for columns. eg data quality. 
c.

2022-05-16 08:55 UTC, navinrathore commented
> a. z col list should just be columns that star with z_ b. StopWordDocumenter should be introduced and included in the ColumnDocumenter. All code and logic for StopWords should go in there. We can then add more documents for columns. eg data quality.

b. Moved the StopWords stuff in a separate class
a.  z col list is indeed formed from 6 z_ columns. Is there any issue in it?

2022-05-16 09:05 UTC, sonalgoyal commented
It will be neater to have a check in the pattern for z columns instead of keeping a list

2022-05-16 09:05 UTC, sonalgoyal commented
Please also rebase this pr as there is a merge conflict

2022-05-16 09:28 UTC, navinrathore commented
> It will be neater to have a check in the pattern for z columns instead of keeping a list

We go for documentation with marked data as input.  It includes field definition fields and only few z_columns. DONT_USE fields also excluded.
But, Documenter is generating docs for all fields (excludes DON'T USE) but includes all z_fields. As of now, only ones part of marked data are shown with hyperlink heading. 
There was some issue working with sequence of columns of marked data. then we moved to get information from FieldDefinition and z Col list.

2022-05-16 10:00 UTC, navinrathore commented
> Please also rebase this pr as there is a merge conflict

resolved conflict.

2022-05-17 07:39 UTC, merged