blockSize - a new config paramter for max size of the block
zinggAI/zingg pull request #272
Opened 2022-05-18 11:59 UTC by navinrathore

2022-05-19 15:01 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Arguments.java
> +	public long getblockSize() {
this will break the json parsing - please also test one end to end case with 120l records and set block size in args. Use debug logs to verify

2022-05-23 09:03 UTC, navinrathore commented on core/src/main/java/zingg/util/Heuristics.java
>  		long maxSize = 8;
Used MIN_SIZE

2022-05-23 09:03 UTC, navinrathore commented on core/src/main/java/zingg/util/Heuristics.java
>  			if (maxSize <= 8) maxSize = 8;
used MIN_SIZE

2022-05-23 09:31 UTC, navinrathore commented
Output:
examples/febrl120k/config.json

```
A. ==================================================
Phase: findTrainingData
blockSize(Config): 150

 2022-05-23 12:38:27,107 [main] INFO  zingg.util.Heuristics - **Block size **12 and total count was 12123
 2022-05-23 12:38:27,121 [main] INFO  zingg.util.Heuristics - Heuristics suggest 12

B ==================================================
Phase: findTrainingData
blockSize(Config): 10

 2022-05-23 13:56:30,606 [main] WARN  zingg.TrainingDataFinder - Read training samples 37 neg 43
 2022-05-23 13:56:31,093 [main] INFO  zingg.TrainingDataFinder - Preprocessing DS for stopWords
 2022-05-23 13:56:50,121 [main] INFO  zingg.util.Heuristics - **Block size **10 and total count was 12035
 2022-05-23 13:56:50,121 [main] INFO  zingg.util.Heuristics - Heuristics suggest 10
 2022-05-23 13:56:50,121 [main] INFO  zingg.util.BlockingTreeUtil - Learning indexing rules for block size 10
 2022-05-23 13:57:00,114 [main] WARN  org.apache.spark.sql.execution.CacheManager - Asked to cache already cached
 
 C ==================================================
Phase: findTrainingData
blockSize(Config): 5
 
  2022-05-23 13:59:39,839 [main] INFO  zingg.TrainingDataFinder - Preprocessing DS for stopWords
 2022-05-23 13:59:58,061 [main] INFO  zingg.util.Heuristics - **Block size **8 and total count was 11993
 2022-05-23 13:59:58,061 [main] INFO  zingg.util.Heuristics - Heuristics suggest 8
 2022-05-23 13:59:58,061 [main] INFO  zingg.util.BlockingTreeUtil - Learning indexing rules for block size 8
 
D ==================================================
Phase: Train
blockSize(Config): 5

 2022-05-23 14:03:44,657 [main] INFO  zingg.util.Heuristics - **Block size **8 and total count was 30406
 2022-05-23 14:03:44,658 [main] INFO  zingg.util.Heuristics - Heuristics suggest 8
 2022-05-23 14:03:44,658 [main] INFO  zingg.util.BlockingTreeUtil - Learning indexing rules for block size 8
 2022-05-23 14:03:59,095 [main] WARN  zingg.util.PipeUtil - Writing output Pipe [name=null, format=PARQUET, preprocessors=null, props={location=models/101/model/block/zingg.block}, schema=null]
 2022-05-23 14:03:59,095 [main] WARN  zingg.util.PipeUtil - Writing file

E ======================================================
Phase: Train
blockSize(Config): 50

ingType,true))]
 2022-05-23 14:08:30,628 [main] INFO  zingg.util.Heuristics - **Block size **30 and total count was 30186
 2022-05-23 14:08:30,629 [main] INFO  zingg.util.Heuristics - Heuristics suggest 30
 2022-05-23 14:08:30,629 [main] INFO  zingg.util.BlockingTreeUtil - Learning indexing rules for block size 30
 2022-05-23 14:08:43,103 [main] WARN  zingg.util.PipeUtil - Writing output Pipe [name=null, format=PARQUET, preprocessors=null, props={location=models/101/model/block/zingg.block}, schema=null]
 2022-05-23 14:08:43,104 [main] WARN  zingg.util.PipeUtil - Writing file
F ======================================================
Phase: Train
blockSize(Config): 25

 2022-05-23 14:11:17,582 [main] INFO  zingg.util.Heuristics - **Block size **25 and total count was 30061
 2022-05-23 14:11:17,582 [main] INFO  zingg.util.Heuristics - Heuristics suggest 25
 2022-05-23 14:11:17,583 [main] INFO  zingg.util.BlockingTreeUtil - Learning indexing rules for block size 25
====================================================== 
```

2022-05-23 09:55 UTC, navinrathore commented
Output:
examples/febrl120k/config.json

```
A. ==================================================
Phase: findTrainingData
blockSize(Config): 150

 2022-05-23 12:38:27,107 [main] INFO  zingg.util.Heuristics - **Block size **12 and total count was 12123
 2022-05-23 12:38:27,121 [main] INFO  zingg.util.Heuristics - Heuristics suggest 12

B ==================================================
Phase: findTrainingData
blockSize(Config): 10

 2022-05-23 13:56:30,606 [main] WARN  zingg.TrainingDataFinder - Read training samples 37 neg 43
 2022-05-23 13:56:31,093 [main] INFO  zingg.TrainingDataFinder - Preprocessing DS for stopWords
 2022-05-23 13:56:50,121 [main] INFO  zingg.util.Heuristics - **Block size **10 and total count was 12035
 2022-05-23 13:56:50,121 [main] INFO  zingg.util.Heuristics - Heuristics suggest 10
 2022-05-23 13:56:50,121 [main] INFO  zingg.util.BlockingTreeUtil - Learning indexing rules for block size 10
 2022-05-23 13:57:00,114 [main] WARN  org.apache.spark.sql.execution.CacheManager - Asked to cache already cached
 
 C ==================================================
Phase: findTrainingData
blockSize(Config): 5
 
  2022-05-23 13:59:39,839 [main] INFO  zingg.TrainingDataFinder - Preprocessing DS for stopWords
 2022-05-23 13:59:58,061 [main] INFO  zingg.util.Heuristics - **Block size **8 and total count was 11993
 2022-05-23 13:59:58,061 [main] INFO  zingg.util.Heuristics - Heuristics suggest 8
 2022-05-23 13:59:58,061 [main] INFO  zingg.util.BlockingTreeUtil - Learning indexing rules for block size 8
 
D ==================================================
Phase: Train
blockSize(Config): 5

 2022-05-23 14:03:44,657 [main] INFO  zingg.util.Heuristics - **Block size **8 and total count was 30406
 2022-05-23 14:03:44,658 [main] INFO  zingg.util.Heuristics - Heuristics suggest 8
 2022-05-23 14:03:44,658 [main] INFO  zingg.util.BlockingTreeUtil - Learning indexing rules for block size 8
 2022-05-23 14:03:59,095 [main] WARN  zingg.util.PipeUtil - Writing output Pipe [name=null, format=PARQUET, preprocessors=null, props={location=models/101/model/block/zingg.block}, schema=null]
 2022-05-23 14:03:59,095 [main] WARN  zingg.util.PipeUtil - Writing file

E ======================================================
Phase: Train
blockSize(Config): 50

ingType,true))]
 2022-05-23 14:08:30,628 [main] INFO  zingg.util.Heuristics - **Block size **30 and total count was 30186
 2022-05-23 14:08:30,629 [main] INFO  zingg.util.Heuristics - Heuristics suggest 30
 2022-05-23 14:08:30,629 [main] INFO  zingg.util.BlockingTreeUtil - Learning indexing rules for block size 30
 2022-05-23 14:08:43,103 [main] WARN  zingg.util.PipeUtil - Writing output Pipe [name=null, format=PARQUET, preprocessors=null, props={location=models/101/model/block/zingg.block}, schema=null]
 2022-05-23 14:08:43,104 [main] WARN  zingg.util.PipeUtil - Writing file
F ======================================================
Phase: Train
blockSize(Config): 25

 2022-05-23 14:11:17,582 [main] INFO  zingg.util.Heuristics - **Block size **25 and total count was 30061
 2022-05-23 14:11:17,582 [main] INFO  zingg.util.Heuristics - Heuristics suggest 25
 2022-05-23 14:11:17,583 [main] INFO  zingg.util.BlockingTreeUtil - Learning indexing rules for block size 25
====================================================== 
```

2022-05-23 10:38 UTC, sonalgoyal requested changes

2022-05-23 13:17 UTC, navinrathore commented on core/src/main/java/zingg/util/Heuristics.java
> +			LOG.debug("**Block size found **");
Restored

2022-05-23 14:15 UTC, merged