More blocking functions
zinggAI/zingg pull request #292
Opened 2022-05-25 11:25 UTC by navinrathore

#261

2022-05-25 11:28 UTC, navinrathore commented
Tested findTrainingData, Train etc. with 1 field for integer, double.
separate commits  for different type of blocking functions. They can be views commit wise.

2022-05-25 11:35 UTC, sonalgoyal requested changes

2022-05-25 11:35 UTC, sonalgoyal commented on core/src/main/java/zingg/hash/TruncateDouble.java
> +	static final int[] POWERS_OF_10 = {1, 10, 100, 1000, 10000, 100000};
why use this? just say 10 exp the argument.

2022-05-25 11:35 UTC, sonalgoyal commented on core/src/test/java/zingg/hash/TestRangeDbl.java
> +		assertEquals(0, value.call((double) 867));
saying 867d makes the code more readable..upto you if you feel that way.

2022-05-25 11:35 UTC, sonalgoyal commented on core/src/test/java/zingg/hash/TestRangeDbl.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
tests for different classes should be in different junit classes. multiple asserts should not go into same unit test, as you dont know then which one broke. If you think it is too much to write junits for the derived classes, just test the main base class.

2022-05-25 11:35 UTC, sonalgoyal commented on core/src/test/java/zingg/hash/TestRangeInt.java
> +	public void testRangeForValueZero() {
same comment as earlier

2022-05-26 04:37 UTC, navinrathore commented on core/src/main/java/zingg/hash/TruncateDouble.java
> +	static final int[] POWERS_OF_10 = {1, 10, 100, 1000, 10000, 100000};
pow() seems a relatively expansive operation.
https://stackoverflow.com/questions/46983772/fastest-way-to-obtain-a-power-of-10

2022-05-26 04:38 UTC, navinrathore commented on core/src/test/java/zingg/hash/TestRangeDbl.java
> +		assertEquals(0, value.call((double) 867));
Shall Make the changes

2022-05-26 04:46 UTC, navinrathore commented on core/src/test/java/zingg/hash/TestRangeDbl.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
I'll change

2022-05-26 04:47 UTC, navinrathore commented on core/src/test/java/zingg/hash/TestRangeInt.java
> +	public void testRangeForValueZero() {
I'll make change

2022-05-26 15:45 UTC, merged