throw error if format is null; happens due to invalid/unsopprted format configuration
zinggAI/zingg pull request #307
Opened 2022-05-31 19:12 UTC by navinrathore

An alternative is if we can throw error at the time of parsing config file when we find that format is not included in zingg list.
Also, we may remove restriction of support of only fixed list of formats. Let Spark throw error if it is an invalid/unsupported format.

Testcases for valid as well as invalid format added.

2022-06-17 04:23 UTC, sonalgoyal requested changes
comments added.

2022-06-17 04:23 UTC, sonalgoyal commented on core/src/test/java/zingg/util/TestPipeUtil.java
> +	public void testGetDataFRameReaderforGivenFormat() throws Exception {
why are we testing with reflection? why not invoke the method directly?

2022-06-17 04:23 UTC, sonalgoyal commented on core/src/test/java/zingg/util/TestPipeUtil.java
> +	public void testGetDataFRameReaderforGivenFormat() throws Exception {
same comment for second testcase

2022-06-17 04:24 UTC, sonalgoyal requested changes
see comments

2022-06-29 08:58 UTC, navinrathore commented
* The PR #370 supersede this PR. Hence, this is being closed.

2022-06-29 08:58 UTC, closed without merging