Python User script support in zingg.sh
zinggAI/zingg pull request #311
Opened 2022-06-06 04:09 UTC by navinrathore

figure out running user scripts from zingg.sh #306

2022-06-06 04:10 UTC, navinrathore commented
Please add if additional/other functionality needed.

2022-06-07 02:23 UTC, sonalgoyal requested changes

2022-06-07 02:23 UTC, sonalgoyal commented on scripts/zingg.sh
> +ZINGG_HOME=./assembly/target
why do we need this?

2022-06-07 07:09 UTC, navinrathore commented on scripts/zingg.sh
> +ZINGG_HOME=./assembly/target
Reverted. erroneously, it was removed.

2022-06-09 05:43 UTC, merged