Updates in Python classes and 'assessModel' python phase
zinggAI/zingg pull request #313
Opened 2022-06-06 20:28 UTC by navinrathore

Implemented requirements listed in 
support preparation New (https://github.com/zinggAI/zingg/discussions/289)  and
New phase assessModel (https://github.com/zinggAI/zingg/issues/296)

2022-06-06 20:30 UTC, navinrathore commented
* PeekModel implementation is due.
* Testcase to write config file based on Arguments object [incomplete due to a serialization issue]

2022-06-07 02:22 UTC, sonalgoyal requested changes

2022-06-07 02:22 UTC, sonalgoyal commented on core/src/main/java/zingg/ZinggBase.java
>  public abstract class ZinggBase implements Serializable, IZingg {
please change ide settings so that tabs/spaces are consistent with older code and do not show up in the diff

2022-06-07 02:22 UTC, sonalgoyal commented on python/phases/assessModel.py
this py script has to be invoked as zingg.sh --phase assessModel --conf conf.json. Arguments can not coded here as then user can not use it for their data.

2022-06-07 02:22 UTC, sonalgoyal commented on python/phases/assessModel.py
> +markedDF = client.getDfFromDs(jMarkedDF)
why do you need markedDF? same for unmarked

2022-06-07 02:22 UTC, sonalgoyal commented on python/phases/assessModel.py
> +confusion_matrix = pd.crosstab(pMarkedDF['z_isMatch'], pMarkedDF['z_prediction'], rownames=['Actual'], colnames=['Predicted'])
please refer to java constants of col names here.

2022-06-07 02:22 UTC, sonalgoyal commented on python/phases/zingg.py
> +
can we refer to the java constants here?

2022-06-09 07:30 UTC, navinrathore commented on core/src/main/java/zingg/ZinggBase.java
>  public abstract class ZinggBase implements Serializable, IZingg {
done

2022-06-09 07:30 UTC, navinrathore commented on python/phases/assessModel.py
> +markedDF = client.getDfFromDs(jMarkedDF)
removed

2022-06-09 07:30 UTC, navinrathore commented on python/phases/assessModel.py
> +confusion_matrix = pd.crosstab(pMarkedDF['z_isMatch'], pMarkedDF['z_prediction'], rownames=['Actual'], colnames=['Predicted'])
Done wherever possible.

2022-06-09 07:31 UTC, navinrathore commented on python/phases/zingg.py
> +
done

2022-06-09 13:58 UTC, merged