Phase recommend
zinggAI/zingg pull request #348
Opened 2022-06-20 04:56 UTC by navinrathore

new phase "recommend' added
Moved StopWordsXXX from Documenter to Recommender/Profiler
fixed relative location of col documents in model.flth

2022-06-20 05:52 UTC, sonalgoyal requested changes

2022-06-20 05:52 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/DataColProfiler.java
> +	public void process(Dataset<Row> data) throws ZinggClientException {
What is the use of process method?

2022-06-20 05:52 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/DataProfiler.java
> +				LOG.info("Read input data : " + data.count());
Please don’t print counts in info - as it is a performance overhead.

2022-06-20 05:52 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/ProfilerBase.java
> +	protected void checkAndCreateDir(String dirName) {
As we are using spark for writing, the folder creation would happen through it, no?

2022-06-20 05:52 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/StopWordsProfiler.java
> +	public void process(Dataset<Row> data) throws ZinggClientException {
Why this method?

2022-06-20 05:52 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/StopWordsProfiler.java
> +	public String getStopWordsDir() {
Move to args

2022-06-20 05:52 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/StopWordsProfiler.java
> +		PipeUtil.write(data, args, ctx, PipeUtil.getStopWordsPipe(args, filenameCSV));
Write with overwrite

2022-06-20 05:52 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/DataProfiler.java
> +				LOG.info("Read input data : " + data.count());
Why do we need the second try catch? Why not use the outer catch as pipe until prints already that it was not able to read a pipe

2022-06-20 05:52 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/DataProfiler.java
> +		data = spark.emptyDataFrame();
Why is an entity df needed?

2022-06-20 07:14 UTC, sonalgoyal commented
Add --column and generate only for that

2022-06-21 06:41 UTC, navinrathore commented on core/src/main/java/zingg/profiler/DataProfiler.java
> +		data = spark.emptyDataFrame();
I think it is there from initial days when Model and Data documenters were combined. It was supposed to run until it is fatal.
However, removed now.

2022-06-21 06:42 UTC, navinrathore commented on core/src/main/java/zingg/profiler/StopWordsProfiler.java
> +		PipeUtil.write(data, args, ctx, PipeUtil.getStopWordsPipe(args, filenameCSV));
Done. For all times, in StopWordPipe.

2022-06-21 06:42 UTC, navinrathore commented on core/src/main/java/zingg/profiler/StopWordsProfiler.java
> +	public String getStopWordsDir() {
done

2022-06-21 06:42 UTC, navinrathore commented on core/src/main/java/zingg/profiler/StopWordsProfiler.java
> +	public void process(Dataset<Row> data) throws ZinggClientException {
Removed

2022-06-21 06:47 UTC, navinrathore commented on core/src/main/java/zingg/profiler/ProfilerBase.java
> +	protected void checkAndCreateDir(String dirName) {
Yes. It would create. removed the check and the function definition.

2022-06-21 06:51 UTC, navinrathore commented on core/src/main/java/zingg/profiler/DataColProfiler.java
> +	public void process(Dataset<Row> data) throws ZinggClientException {
As there may be local col profiling in addition to that in other specific classes, if any. This function has been there when things were combined. In DataDocumenter, only this function is enough to call.

2022-06-21 08:58 UTC, navinrathore commented on core/src/main/java/zingg/profiler/DataProfiler.java
> +				LOG.info("Read input data : " + data.count());
Count() removed.
Outer catch removed. exception, if any, will be pass to higher in call stack.

2022-06-21 09:00 UTC, navinrathore commented
Removed an Reflection call.

2022-06-21 15:08 UTC, sonalgoyal reviewed
rename all classes to recommender/package to recommend instead of profiler

2022-06-21 15:12 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/ProfilerBase.java
> +	protected void checkAndCreateDir(String dirName) {
i still see this?

2022-06-21 15:14 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/DataColProfiler.java
> +			LOG.info("No Stop Words document generated");
it is a recommendation - please update error message

2022-06-21 15:22 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/DataProfiler.java
> +	protected static String name = "zingg.DataProfiler";
are we using name anywhere?

2022-06-21 15:22 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/StopWordsProfiler.java
> +			data = data.select(split(data.col(fieldName), "\\s+").as("split"));
column names created by Zingg are defined centrally in ColNames - all of them have z_ prefix

2022-06-21 15:22 UTC, sonalgoyal commented on core/src/main/java/zingg/profiler/StopWordsProfiler.java
> +			data = data.groupBy("word").count().orderBy(desc("count"));
can we filter the data based on the cutoff and then orderby? it may be faster

2022-06-21 15:22 UTC, sonalgoyal commented on core/src/main/resources/model.ftlh
> +    <th class="border-right border-white" > <a href="${columns[entityIndex]}.html"> ${columns[entityIndex]!} </a></th>
do we still need the links? what are we showing here when we click?

2022-06-21 15:22 UTC, sonalgoyal commented on core/src/test/java/zingg/profiler/TestStopWordsProfiler.java
> +package zingg.profiler;
the main test here should not be reading/writing files but if we are generating the write stop words. just build a dataset in memory and use that as your dataset for testing?

2022-06-21 15:22 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Client.java
> +		if (options.get(ClientOptions.COLUMN)!= null) {
can we have a test here to see this is getting set correctly?

2022-06-21 15:22 UTC, sonalgoyal requested changes
added comments, please check

2022-06-22 06:19 UTC, navinrathore commented on client/src/main/java/zingg/client/Arguments.java
> +	String column = "";
Other option is "null".

2022-06-27 03:25 UTC, navinrathore commented on client/src/main/java/zingg/client/Arguments.java
> +	String column = "";
Set it uninitialized that is nothing but a null.

2022-06-27 03:26 UTC, navinrathore commented on core/src/main/java/zingg/profiler/ProfilerBase.java
> +package zingg.profiler;
Removed the class

2022-06-27 03:29 UTC, navinrathore commented on core/src/main/java/zingg/util/PipeUtil.java
>  		p.setProp(FilePipe.HEADER, "true");
Added testcase

2022-06-27 03:30 UTC, navinrathore commented on core/src/main/java/zingg/profiler/StopWordsProfiler.java
> +	protected static String name = "zingg.StopWordsProfiler";
Removed.

2022-06-27 03:31 UTC, navinrathore commented on core/src/main/java/zingg/profiler/DataColProfiler.java
> +			LOG.info("No Stop Words document generated");
Updated to "No stopwords generated"

2022-06-27 03:32 UTC, navinrathore commented on core/src/main/java/zingg/profiler/DataProfiler.java
> +	protected static String name = "zingg.DataProfiler";
DataProfiler and DataColProfiler are the two classes. Removed DataColProfiler and moved applicable stuff in the class DataProfiler,

2022-06-27 03:33 UTC, navinrathore commented on core/src/main/java/zingg/profiler/StopWordsProfiler.java
> +			data = data.select(split(data.col(fieldName), "\\s+").as("split"));
Made them local consts only. They are not reusable column names.

2022-06-27 05:13 UTC, navinrathore commented on core/src/main/java/zingg/profiler/StopWordsProfiler.java
> +			data = data.groupBy("word").count().orderBy(desc("count"));
Stopwords chosen whose count is greaterThan(sum(col(count))* cuttoff); 
No more orderBy()
**Still Need review of function findStopWords() as the result size may be UN-predictable. Largely depend on how many words are there in dataset"**

2022-06-27 05:16 UTC, navinrathore commented on client/src/main/java/zingg/client/Client.java
> +		if (options.get(ClientOptions.COLUMN)!= null) {
Yes. Added the testcase.

2022-06-27 09:39 UTC, navinrathore commented on core/src/test/java/zingg/profiler/TestStopWordsProfiler.java
> +package zingg.profiler;
Removed such tests. added one wherein dataset is created programmatically.

2022-06-27 10:21 UTC, navinrathore commented on core/src/main/java/zingg/profiler/ProfilerBase.java
> +	protected void checkAndCreateDir(String dirName) {
ProfilerBase.java itself has been removed.

2022-06-27 11:55 UTC, navinrathore commented
#336

2022-06-29 08:43 UTC, navinrathore commented
[Everywhere names comprising profiler changed to that of recommender(individual commit)](https://github.com/zinggAI/zingg/pull/348/commits/18575f060f42c37ef459a865f4574848fe925908)

2022-07-05 01:11 UTC, sonalgoyal requested changes

2022-07-05 01:11 UTC, sonalgoyal commented on core/src/test/java/zingg/recommender/TestStopWordsRecommender.java
> +		Map<String, Integer> map = Stream.of(new Object[][] {
The data creation here is leading to a lot of extra loops and object creation. Use of a hash when 

I feel a simpler logic would be
- define a class word, count (the, 44)
- define a list of words. just add all the words one by one. 
- define wordDistribution - int[][] row is NO_OF_RECORDS, each column represents a word
- fill wordDistribution per word in the list of words
- iterate over the wordDist array and join the strings by looking up the col index. 

Also define structType once and reuse?

2022-07-16 08:09 UTC, closed without merging