more python examples issue #337
zinggAI/zingg pull request #364
Opened 2022-06-24 05:44 UTC by RavirajBaraiya

2022-06-28 00:39 UTC, sonalgoyal requested changes

2022-06-28 00:39 UTC, sonalgoyal commented on examples/amazon-google/AmazonGoogle.py
> +PipeA = CsvPipe("test")
Rename a and b to Amazon and google. Also all our variables start with small case, and we follow camel casing

2022-06-28 00:39 UTC, sonalgoyal commented on examples/amazon-google/AmazonGoogle.py
> +outputPipeG.setLocation("/tmp")
Why do we need two outputs? We just want to do a link

2022-06-28 00:39 UTC, sonalgoyal commented on examples/iTunes-amazon/iTunesAmazon.py
> +Song_Name = FieldDefinition("Song_Name", "string", MatchType.FUZZY)
Same comments as above

2022-06-28 00:39 UTC, sonalgoyal commented on examples/amazon-google/AmazonGoogle.py
> +options.setPhase("trainMatch")
We should set link as the phase

2022-07-05 08:59 UTC, RavirajBaraiya commented
ncVoter example is not tested successfully because of less RAM

2022-07-07 04:38 UTC, RavirajBaraiya commented
@sonalgoyal added new commits for issue #337

2022-07-07 07:20 UTC, sonalgoyal commented
Sorry I still see the (C) issue in the data - can you please clean up the
pr?

Cheers,
Sonal
https://github.com/zinggAI/zingg



On Thu, Jul 7, 2022 at 10:08 AM RavirajBaraiya ***@***.***>
wrote:

> @sonalgoyal <https://github.com/sonalgoyal> added new commits for issue
> #337 <https://github.com/zinggAI/zingg/issues/337>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zinggAI/zingg/pull/364#issuecomment-1177057497>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACLRCZV7Y6VR62TUPG7X3DVSZNLNANCNFSM5ZWTDKCA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-07 07:57 UTC, RavirajBaraiya commented
@sonalgoyal unchanged googleProduct.csv

2022-07-07 08:45 UTC, sonalgoyal commented
i still see some changes. better would be to remove this file from the pr.
Cheers,
Sonal
https://github.com/zinggAI/zingg



On Thu, Jul 7, 2022 at 1:27 PM RavirajBaraiya ***@***.***>
wrote:

> @sonalgoyal <https://github.com/sonalgoyal> unchanged googleProduct.csv
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zinggAI/zingg/pull/364#issuecomment-1177218293>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACLRC7KSYY6XW3TVID7GPDVS2EX5ANCNFSM5ZWTDKCA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-07 10:34 UTC, closed without merging