Double similarity function - null pointer exception
zinggAI/zingg pull request #369
Opened 2022-06-28 05:59 UTC by navinrathore

* fixed config.json as MatchType NUMERIC_WITH_UNITS changed to NUMBER_WITH_UNITS
* 'null' checks in DoubleSimilarityFunction. Also, checked for Double.NAN

2022-06-28 06:03 UTC, navinrathore commented
Tested with febrl standard dataset and another updated with Double field/values
with amazon-google dataset
with iTunes-amazon dataset

2022-06-28 06:10 UTC, navinrathore commented
Noticed that, for amazon-google dataset, header for google.csv file is not compatible with names in schema. Though, zingg seems working fine but below is the message.
```
2022-06-28 11:39:15,950 [main] WARN  zingg.util.PipeUtil - Reading Pipe [name=google, format=CSV, preprocessors=null, props={location=examples/amazon-google/GoogleProducts.csv, delimiter=,, header=true}, schema=StructType(StructField(id,StringType,false), StructField(title,StringType,true), StructField(description,StringType,true), StructField(manufacturer,StringType,true), StructField(price,DoubleType,true))]
 2022-06-28 11:39:16,248 [Executor task launch worker for task 1.0 in stage 10.0 (TID 39)] WARN  org.apache.spark.sql.catalyst.csv.CSVHeaderChecker - CSV header does not conform to the schema.
 Header: id, name, description, manufacturer, price
 Schema: id, title, description, manufacturer, price
Expected: title but found: name
CSV file: file:///home/navin/workDir/zingg-1/examples/amazon-google/GoogleProducts.csv

```

2022-06-28 06:11 UTC, navinrathore commented
* #351

2022-07-04 07:37 UTC, sonalgoyal requested changes
- Add tests for some doubles.
- Rename variable

2022-07-04 07:37 UTC, sonalgoyal commented on core/src/test/java/zingg/similarity/function/TestDoubleSimilarityFunction.java
> +		DoubleSimilarityFunction isNull = new DoubleSimilarityFunction();
name of variable?

2022-07-05 08:59 UTC, navinrathore commented on core/src/test/java/zingg/similarity/function/TestDoubleSimilarityFunction.java
> +		DoubleSimilarityFunction isNull = new DoubleSimilarityFunction();
changed to simFn

2022-07-05 09:00 UTC, navinrathore commented on core/src/test/java/zingg/similarity/function/TestDoubleSimilarityFunction.java
> +		DoubleSimilarityFunction isNull = new DoubleSimilarityFunction();
Added some tests

2022-07-13 08:49 UTC, merged