changed 'Format' type from Enum to Class to support new formats by default
zinggAI/zingg pull request #370
Opened 2022-06-29 05:46 UTC by navinrathore

* changes made for **Format** class to behave as close as possible earlier enum avatar.
* **PipeFactory** class seems redundant as of now. Particularly, its register() function. Therefore, its getPipe() functions has hardcoded format types. switch statement supports enum or constants only.

2022-06-29 06:23 UTC, navinrathore commented
* Tested with mysql apart from csv. Parquet is internally used at multiple place.
* Tried ORC format as well. it could read file.
* In fact, tested with CSV, Parquet removed from the Format class and things worked properly. This suggests it should work any supported format.
* For bad formats. the following error message prints from thrown exception in addition to local message.
```
2022-06-29 11:46:29,053 [main] WARN  zingg.util.PipeUtil - 
Failed to find data source: csv2. Please find packages at http://spark.apache.org/third-party-projects.html
 2022-06-29 11:46:30,786 [main] WARN  zingg.client.Client - 
Apologies for this message. Zingg has encountered an error. Could not read data.

```
the actual thrown exception is below. (not printed).
```
java.lang.ClassNotFoundException: Failed to find data source: badFormat. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:692)
```

2022-06-29 06:52 UTC, navinrathore commented
After the enum to class change, it is now mandatory for Pipe to have not-null format. Shall be put this restriction somehow?
InMemoryPipe, JDBCPipe have required such change.

2022-07-05 01:33 UTC, sonalgoyal requested changes
Do you think we could remove Format class altogether and just keep it as Pipe and String format?

2022-07-05 09:16 UTC, navinrathore commented
> Do you think we could remove Format class altogether and just keep it as Pipe and String format?

Yes. we can. Though, It has got references/usage at multiple places.

2022-07-06 15:41 UTC, closed without merging