TCs for String Similarity Distance function
zinggAI/zingg pull request #371
Opened 2022-06-30 05:51 UTC by navinrathore

* Used JaccSimFunction class for instanciation as StringSimilarityDistanceFunction is an abstract class.
* Added TC for specific sample strings as inputs.

2022-06-30 05:52 UTC, navinrathore commented
* TCs for issue #353

2022-07-04 07:34 UTC, sonalgoyal requested changes

2022-07-04 07:34 UTC, sonalgoyal commented on core/src/test/java/zingg/similarity/function/TestJaccSimFunction.java
> +	}
please make the string smaller and put actual similarity by using set overlap

2022-07-05 09:41 UTC, navinrathore commented on core/src/test/java/zingg/similarity/function/TestJaccSimFunction.java
> +		assertFalse(score == 0d || score == 1d);
Added actual values. Not sure the score values are correct, values are taken from secondstring output

2022-07-16 07:50 UTC, merged