Added specific pipes property constants
zinggAI/zingg pull request #374
Opened 2022-07-01 13:58 UTC by navinrathore

2022-07-01 13:59 UTC, navinrathore commented
* takes care of a part of https://github.com/zinggAI/zingg/issues/347

2022-07-05 01:26 UTC, sonalgoyal commented on python/zingg/pipes/pipes.py
> +        Pipe.addProperty(self, JBigQueryPipe.VIEWS_ENABLED, "true")
can we add this property by default?

2022-07-05 01:28 UTC, sonalgoyal requested changes

2022-07-05 01:28 UTC, sonalgoyal commented on python/zingg/pipes/pipes.py
>          Pipe.addProperty(self, FilePipe.HEADER,"true")
this is wrong - we can not set header default true. we have to let the user set the values.

2022-07-05 09:46 UTC, navinrathore commented on python/zingg/pipes/pipes.py
>          Pipe.addProperty(self, FilePipe.HEADER,"true")
I've removed it now.

2022-07-05 09:47 UTC, navinrathore commented on python/zingg/pipes/pipes.py
> +        Pipe.addProperty(self, JBigQueryPipe.VIEWS_ENABLED, "true")
In Java app, there are no settings for BigQueryPipe,

2022-07-07 09:37 UTC, navinrathore commented
> please add newlines between python methods.
Already in the code base
https://github.com/zinggAI/zingg/blob/main/python/zingg/pipes/pipes.py
through the below PR (for same comment here) 
https://github.com/zinggAI/zingg/pull/376#discussion_r913627667

2022-07-07 09:48 UTC, navinrathore commented on python/zingg/pipes/pipes.py
> +        Pipe.addProperty(self, JBigQueryPipe.VIEWS_ENABLED, "true")
Property is no more set here.

2022-07-11 18:41 UTC, merged