added stopword functionality in zingg FieldDefinition
zinggAI/zingg pull request #392
Opened 2022-07-13 11:15 UTC by RavirajBaraiya

added setStopWordsCutoff method in zingg.Arguments class
added setStopWords method in zingg.FeildDefinition class
added stopword parameter in one field of amazon-google and iTunes-amazon examples

2022-07-13 11:19 UTC, RavirajBaraiya commented
issue #340

2022-07-13 12:15 UTC, RavirajBaraiya commented
issue #252 
added new config files for "Amazon-google" dataset involving stop word removal.

2022-07-13 19:27 UTC, sonalgoyal commented on examples/stopWords.csv
> +StopWord
move this file into amazon google and update code and config accordingly

2022-07-13 19:29 UTC, sonalgoyal requested changes
move the stop words file under the relevant example folder and use from there.

2022-07-14 09:31 UTC, RavirajBaraiya commented on examples/stopWords.csv
> +StopWord
moved csv to amazon-google

2022-07-16 04:17 UTC, merged