Stop words recommender working
zinggAI/zingg pull request #491
Opened 2023-02-27 12:35 UTC by vikasgupta78

Changes to make Stop words recommender working

2023-02-27 14:55 UTC, sonalgoyal requested changes
please see changes

2023-02-27 14:55 UTC, sonalgoyal commented on spark_zingg/core/src/main/java/zingg/spark/SparkStopWordsRecommender.java
> +
the logic of this method should be in the common class

2023-02-27 14:55 UTC, sonalgoyal commented on common/core/src/main/java/zingg/recommender/StopWordsRecommender.java
> -	public ZFrame<D,R,C> findStopWords(ZFrame<D,R,C> data, String fieldName) {
see other comment. this base class should have all the logic for building stop words so that we can use across snow and spark.

2023-02-28 07:37 UTC, vikasgupta78 commented on spark_zingg/core/src/main/java/zingg/spark/SparkStopWordsRecommender.java
> +
i have tried to fix it in commit 771ae6a, please have a look. let me know if more improvement is needed

2023-02-28 07:37 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/recommender/StopWordsRecommender.java
> -	public ZFrame<D,R,C> findStopWords(ZFrame<D,R,C> data, String fieldName) {
i have tried to fix it in commit 771ae6a, please have a look. let me know if more improvement is needed

2023-02-28 07:40 UTC, vikasgupta78 commented
i have tried to fix it in commit 771ae6a, please have a look. let me know if more improvement is needed

2023-02-28 08:29 UTC, closed without merging