Stop words preprocessor and junits
zinggAI/zingg pull request #500
Opened 2023-03-02 13:50 UTC by vikasgupta78

Stop words preprocessor and junits

2023-03-05 08:11 UTC, sonalgoyal requested changes

2023-03-06 04:24 UTC, vikasgupta78 commented on common/client/src/main/java/zingg/client/ZFrame.java
> +public interface ZFrame<D, R, C> extends Serializable{
fixed in commit a350297

2023-03-06 06:13 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/preprocess/StopWords.java
> +public abstract class StopWords<S,D,R,C,T> implements Serializable{
done in commit db207e7 and e8220d4

2023-03-06 06:37 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/preprocess/StopWords.java
>  		List<String> wordList = new ArrayList<String>();
done in d34fa3b

2023-03-06 06:41 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/TrainingDataFinder.java
> +					ZFrame<D,R,C> posSamples = getStopWords().preprocessForStopWords(posSamplesOriginal);
As discussed neg preprocess not needed as already done for training file

2023-03-06 08:18 UTC, vikasgupta78 commented on spark_zingg/core/src/main/java/zingg/spark/preprocess/SparkStopWords.java
> +		Dataset<Row> dfAfterRemoval = ds.df().withColumn(fieldName,callUDF(udfName, ds.df().col(fieldName)));
changed to udf2 in commit a46ccd9

2023-03-06 09:36 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/preprocess/StopWords.java
> +	protected String stopWordColumn = ColName.COL_WORD;
done in commit e2d8358

2023-03-06 09:36 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/preprocess/StopWords.java
> +				String pattern = getPattern(wordList);
done as part of e2d8358

2023-03-06 09:48 UTC, merged