improving code coverage issue #615
zinggAI/zingg pull request #616
Opened 2023-06-20 19:04 UTC by Manan-S0ni

#615
improving code coverage for zingg/common/core:
/hash to 97% coverage
model and sink both to 100% coverage

2023-06-29 12:11 UTC, sonalgoyal requested changes

2023-06-29 12:11 UTC, sonalgoyal commented on common/core/src/test/java/zingg/hash/TestIdentityLong.java
> +    public void testIdentityLong1() {
rename to testNullValue

2023-06-29 12:11 UTC, sonalgoyal commented on common/core/src/test/java/zingg/hash/TestLessThanZeroFloat.java
> +import static org.junit.jupiter.api.Assertions.assertFalse;
this is a good test

2023-06-29 12:11 UTC, sonalgoyal commented on common/core/src/test/java/zingg/hash/TestTrimLastDigitsFloat.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
can you please test for negative values as well

2023-06-29 12:11 UTC, sonalgoyal commented on common/core/src/test/java/zingg/hash/TestRangeBetween100And1000Long.java
> +
what happens if you give a range say -10 and -100? What happens with 0,0? see if you can break these functions.

2023-06-30 14:04 UTC, Manan-S0ni commented on common/core/src/test/java/zingg/common/core/sink/TestTableOutput.java
> +package zingg.common.core.sink;
Noted

2023-11-21 06:43 UTC, sonalgoyal commented
@vikasgupta78 can you pease get this to completion?

2023-12-14 14:20 UTC, vikasgupta78 commented
@gnanaprakash-ravi if you have time can you look at this and incorporate review comments as suggested by Sonal

2023-12-14 14:33 UTC, gnanaprakash-ravi commented
Sure, I will look into it!!

2023-12-14 15:49 UTC, sonalgoyal commented
I have some ideas on this one, so please talk to me before you start

2024-10-09 09:43 UTC, closed without merging