Added Google Analytics for telemetry #41
zinggAI/zingg pull request #68
Opened 2021-12-09 03:58 UTC by navinrathore

Here is the PR for Anonymous Telemetry GH-41. Please review and provide inputs.

Few things to be noted:
a) Pipes can have multiple values. currently only last value set is only becoming part of parameter string.
b) (one or more) event structure (captured parameters) must be formalized based on how data has to be put on GA dashboard
c) Analytics.md shall be shared later

2021-12-09 04:11 UTC, navinrathore commented
sonalgoyal4@gmail.com has been given FULL rights to test with GA account(Property zinggBothAnalyticsProps - GA4)
The branch is https://github.com/navinrathore/zingg-1/tree/zAnalytics

2021-12-09 06:58 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Arguments.java
> +			LOG.warn("CollectMetricsFlag is " + args.getCollectMetricsFlag());
case of flag - collectMetricsFlag

2021-12-09 07:50 UTC, sonalgoyal requested changes

2021-12-09 07:50 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Client.java
> +		LOG.info("*   For more details, refer to the analytics document(docs.zingg.ai)       *");
please refer to actual doc

2021-12-09 07:50 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Client.java
>  			client = new Client(arguments, options);
else print no analytics are being collected

2021-12-09 07:50 UTC, sonalgoyal commented on core/src/main/java/zingg/Labeller.java
> +			if (args.getCollectMetricsFlag()) {
can the flag check happen in analytics class by sending the arguments object or the flag in the method? that way we dont have to write the ifs everywhere

2021-12-09 07:50 UTC, sonalgoyal commented on core/src/main/java/zingg/Labeller.java
> +				Analytics.getSpecificParams().put("labelData", String.valueOf(unmarkedRecords.count()));
can we call it labelDataCount?

2021-12-09 07:50 UTC, sonalgoyal commented on core/src/main/java/zingg/Matcher.java
> +				Analytics.getSpecificParams().put("testData", String.valueOf(testData.count()));
this will get costly, please use approxcount

2021-12-09 07:50 UTC, sonalgoyal commented on core/src/main/java/zingg/Matcher.java
> +				Analytics.getSpecificParams().put("testData", String.valueOf(testData.count()));
also dataCount - why is it testData?

2021-12-09 07:50 UTC, sonalgoyal commented on core/src/main/java/zingg/Matcher.java
> +				Analytics.getSpecificParams().put("testData", String.valueOf(testData.count()));
can we define an interface with metrics names and methods for calculating the metrics? approxCount(Dataset<Row>..) count(Dataset<Row>..) - that way all metrics are in one place

2021-12-09 07:50 UTC, sonalgoyal commented on core/src/main/java/zingg/Trainer.java
> +				Analytics.getSpecificParams().put("testData", String.valueOf(testData.count()));
cant the getSpecificParams method take a long and convert to string internally?

2021-12-09 07:50 UTC, sonalgoyal commented on core/src/main/java/zingg/Trainer.java
> +				Analytics.getSpecificParams().put("features", String.valueOf(getFeaturers().size()));
we dont need to track this

2021-12-09 07:50 UTC, sonalgoyal commented on client/src/main/java/zingg/client/util/Analytics.java
> +		LOG.debug("Event tracked.");
warn ?

2021-12-09 07:50 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Arguments.java
> +	boolean collectMetricsFlag = true;
rename to collectMetrics

2021-12-09 07:50 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Client.java
> +			if (client.getArguments().getCollectMetricsFlag()) {
trackMetrics is already checking for the flag, no need for an if here

2021-12-09 07:50 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Client.java
> +		Pipe[] dataPipes = getArguments().getData();
we can add all the types here instead of just the last one?

2021-12-09 07:50 UTC, sonalgoyal commented on core/src/main/java/zingg/Labeller.java
> +				Analytics.getSpecificParams().put("labelData", String.valueOf(unmarkedRecords.count()));
actually we do not need unmarked label count, only labelled data count in the train phase.

2021-12-09 07:50 UTC, sonalgoyal commented on core/src/main/java/zingg/TrainingDataFinder.java
> +					Analytics.getSpecificParams().put("trainingData", String.valueOf(data.count()));
no need for this metric.

2021-12-09 07:50 UTC, sonalgoyal commented on core/src/main/java/zingg/Matcher.java
> +				Analytics.getSpecificParams().put("testData", String.valueOf(testData.count()));
eventually 105-107 will become Analytics.track(Metric.NAME, Metric.approaxCount(testData))

2021-12-09 07:50 UTC, sonalgoyal commented on client/src/main/java/zingg/client/util/Analytics.java
> +
please comment out ua code if any

2021-12-09 07:50 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Arguments.java
> +	boolean collectMetricsFlag = true;
Need analytics.md

2021-12-09 07:50 UTC, sonalgoyal commented on core/src/main/java/zingg/Matcher.java
> +				Analytics.getSpecificParams().put("testData", String.valueOf(testData.count()));
All metrics params to be documented

2021-12-10 04:47 UTC, navinrathore commented on client/src/main/java/zingg/client/Client.java
>  			client = new Client(arguments, options);
done

2021-12-10 04:47 UTC, navinrathore commented on client/src/main/java/zingg/client/Client.java
> +		LOG.info("*   For more details, refer to the analytics document(docs.zingg.ai)       *");
added fully qualified link to the doc
added appropriate message in ELSE

2021-12-10 04:50 UTC, navinrathore commented on client/src/main/java/zingg/client/Arguments.java
> +			LOG.warn("CollectMetricsFlag is " + args.getCollectMetricsFlag());
Changed and "flag" removed

2021-12-10 04:51 UTC, navinrathore commented on client/src/main/java/zingg/client/Arguments.java
> +	boolean collectMetricsFlag = true;
renamed flag. Created Document

2021-12-10 04:51 UTC, navinrathore commented on client/src/main/java/zingg/client/Client.java
> +			if (client.getArguments().getCollectMetricsFlag()) {
Removed unnecessary checks everywhere.

2021-12-10 04:52 UTC, navinrathore commented on core/src/main/java/zingg/TrainingDataFinder.java
> +					Analytics.getSpecificParams().put("trainingData", String.valueOf(data.count()));
Removed

2021-12-10 04:53 UTC, navinrathore commented on client/src/main/java/zingg/client/util/Analytics.java
> +
There is only UA4 related code only

2021-12-10 04:54 UTC, navinrathore commented on client/src/main/java/zingg/client/util/Analytics.java
> +
However, API_SECRET and MEASUREMENT_ID for the LIVE account needs to be generated and added here

2021-12-10 10:16 UTC, navinrathore commented on core/src/main/java/zingg/Matcher.java
> +				Analytics.getSpecificParams().put("testData", String.valueOf(testData.count()));
Made changes as per details and discussion

2021-12-10 10:17 UTC, navinrathore commented on client/src/main/java/zingg/client/Client.java
> +		Pipe[] dataPipes = getArguments().getData();
This is due. I will show the strings generated when sent as array or like.. they take separate entries.

2021-12-10 10:17 UTC, navinrathore commented on core/src/main/java/zingg/Labeller.java
> +				Analytics.getSpecificParams().put("labelData", String.valueOf(unmarkedRecords.count()));
done

2021-12-10 10:20 UTC, navinrathore commented on core/src/main/java/zingg/Labeller.java
> +			if (args.getCollectMetricsFlag()) {
I kept it like this. I think checking a flag is very less resource consuming than calling a function.
If you say so, I will make this change.

2021-12-10 11:09 UTC, sonalgoyal requested changes

2021-12-10 11:10 UTC, sonalgoyal commented
Metrics names to not have underscores, use camel casing. No_features to be renamed to numFeatures

2021-12-10 11:11 UTC, sonalgoyal commented
Flag check should be in the analytics method as discussed earlier

2021-12-10 11:12 UTC, sonalgoyal commented
Why can’t we make the call to analytics as analytics.track instead of analytics.get specific params.track?

2021-12-10 11:13 UTC, sonalgoyal commented on core/src/main/java/zingg/Labeller.java
> +			if (args.getCollectMetricsFlag()) {
It’s more about readability. Also if someone just calls the method with their checking the flag, we introduce an error by collecting the metrics even when the flag is off. Better to have the action method take care of it in one place

2021-12-10 11:18 UTC, sonalgoyal commented
Please name all metrics same as actual config variables so it is easier to understand where they are coming from

2021-12-10 11:19 UTC, sonalgoyal commented
Other items due before we pull this in - docker testing, analytics.MD, multiple pipes

2021-12-11 07:28 UTC, sonalgoyal requested changes

2021-12-11 07:28 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Client.java
> +			LOG.info("*  please refer to the zingg docs (https://docs.zingg.ai/docs/analytics.html)     *");
this line is off, can we please make sure the banner is centered?

2021-12-11 07:28 UTC, sonalgoyal commented on client/src/main/java/zingg/client/util/Analytics.java
> +		} catch (URISyntaxException e) {
can we combine the two try catch?

2021-12-11 07:28 UTC, sonalgoyal commented on client/src/main/java/zingg/client/util/Metric.java
> +    public static final String METRIC_SOURCE_TYPE = "source_type";
METRIC_ is redundant, we are always referrring to these attributes as Metric.something which denotes that it is a metric. please remove

2021-12-11 07:28 UTC, sonalgoyal commented on client/src/main/java/zingg/client/util/Metric.java
> +    public static final String METRIC_FEATURE_COUNT = "no_features";
we need two metrics - total number of fields in the data(numTotalFields) and fields which have been configured NOT as dont_use in fieldDefinitions. (numMatchFields)

2021-12-11 07:28 UTC, sonalgoyal commented on docs/analytics.md
> +* **Execution Time:** Approximate execution time of the program
why is it approximate?

2021-12-11 07:28 UTC, sonalgoyal commented on docs/analytics.md
> +* **Program Run count:** How many times Zingg has run for particular phase (Label, Train, Match)
we are firing event per run, but not counting explicitly the total counts.

2021-12-11 07:28 UTC, sonalgoyal commented on docs/analytics.md
> +* **Positive and Negative records count:** For train phase, number of positive and negative records
user does not have the concept of positive and negative but marked matches and non matches

2021-12-11 14:02 UTC, navinrathore commented on client/src/main/java/zingg/client/Client.java
> +			LOG.info("*  please refer to the zingg docs (https://docs.zingg.ai/docs/analytics.html)     *");
Already rectified

2021-12-11 14:11 UTC, navinrathore commented on client/src/main/java/zingg/client/util/Metric.java
> +    public static final String METRIC_SOURCE_TYPE = "source_type";
Removed

2021-12-11 14:11 UTC, navinrathore commented on client/src/main/java/zingg/client/util/Analytics.java
> +		} catch (URISyntaxException e) {
Combined

2021-12-11 14:52 UTC, navinrathore commented on docs/analytics.md
> +* **Program Run count:** How many times Zingg has run for particular phase (Label, Train, Match)
Removed the entry

2021-12-11 16:34 UTC, sonalgoyal requested changes

2021-12-11 16:34 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Client.java
> +			LOG.info("*  refer to the zingg docs (https://docs.zingg.ai/docs/analytics.html)     *");
zingg - Z caps

2021-12-11 16:34 UTC, sonalgoyal commented on client/src/main/java/zingg/client/util/Analytics.java
> +	public static final Log LOG = LogFactory.getLog(Analytics.class);
move to beginning of class

2021-12-11 16:34 UTC, sonalgoyal commented on core/src/main/java/zingg/Matcher.java
> +			double count = testData.count();
wasnt the count long? please check

2021-12-11 16:50 UTC, navinrathore commented on docs/analytics.md
> +* **Execution Time:** Approximate execution time of the program
removed

2021-12-11 16:50 UTC, navinrathore commented on client/src/main/java/zingg/client/util/Metric.java
> +    public static final String METRIC_FEATURE_COUNT = "no_features";
Done

2021-12-11 16:58 UTC, navinrathore commented on core/src/main/java/zingg/Matcher.java
> +			double count = testData.count();
changed to long

2021-12-11 16:58 UTC, navinrathore commented on client/src/main/java/zingg/client/util/Analytics.java
> +	public static final Log LOG = LogFactory.getLog(Analytics.class);
done

2021-12-11 16:58 UTC, navinrathore commented on client/src/main/java/zingg/client/Client.java
> +			LOG.info("*  refer to the zingg docs (https://docs.zingg.ai/docs/analytics.html)     *");
done

2021-12-11 17:00 UTC, navinrathore commented on docs/analytics.md
> +* **Positive and Negative records count:** For train phase, number of positive and negative records
Changed to Mached & Nonmached

2021-12-11 18:12 UTC, sonalgoyal commented on docs/analytics.md
> +title: Zingg Models
title of page

2021-12-11 18:23 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Client.java
> +		String inPipesStr = Arrays.stream(dataPipes)
move method to pipeutil and use for both data and output

2021-12-13 06:09 UTC, navinrathore commented on client/src/main/java/zingg/client/Client.java
> +		String inPipesStr = Arrays.stream(dataPipes)
Done

2021-12-13 06:10 UTC, navinrathore commented on docs/analytics.md
> +title: Zingg Models
changed

2021-12-17 14:57 UTC, merged