Issue #692 obv dupe changes for ftd and matcher
zinggAI/zingg pull request #694
Opened 2023-10-18 14:16 UTC by vikasgupta78

Issue #692 obv dupe changes for ftd and matcher

2023-10-19 00:53 UTC, sonalgoyal requested changes

2023-10-19 00:53 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/executor/ObvDupeFilter.java
> +package zingg.common.core.executor;
this class is not an executor and should be broken down into two classes at least. they can live in a separate package zingg.common.core.obviousDupes. one that takes args, dsutil and creates filters. one that applies those.

2023-10-19 00:53 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/executor/Matcher.java
>  			ZFrame<D, R, C> obvDupePairs = getObvDupePairs(blocked);
this logic should move to obvious dupes. the matcher should just ask the obv dupes to add/remove dupes as necessary by passing blocks/pairs whatever

2023-10-19 00:53 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/executor/ObvDupeFilter.java
> +	public C getObviousDupesFilter(ZFrame<D, R, C> df1, ZFrame<D, R, C> dfToJoin, String obviousDupeString, C extraAndCond) {
if you define the obvious filter not through a string put through json, this code becomes much simpler. how about 

"obviousDupes": [
"matchCondition": [{"column":"fname"},{"column":"lname"}]
"matchCondition":[{}]
]

You can simply define this object as part of the args. It gets populated automatically, no need to parse, trim etc.

2023-10-19 03:03 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/executor/Matcher.java
>  			ZFrame<D, R, C> obvDupePairs = getObvDupePairs(blocked);
The logic is already moved , this method delegates work to the obv dupe class. The method is kept as it gets overriden in enterprise matcher for purpose of instrumentation

2023-10-19 03:05 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/executor/Matcher.java
>  			ZFrame<D, R, C> obvDupePairs = getObvDupePairs(blocked);
That is getObvDupePairs method in Matcher

2023-10-19 03:06 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/executor/ObvDupeFilter.java
> +	public C getObviousDupesFilter(ZFrame<D, R, C> df1, ZFrame<D, R, C> dfToJoin, String obviousDupeString, C extraAndCond) {
Will create a JSON sample for various scenarios and get it reviewed before implementation

2023-10-19 03:07 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/executor/ObvDupeFilter.java
> +package zingg.common.core.executor;
I had thought that may be we might want to create a phase out of it in future? 100% match filter kinds? If no such plan can break it down, no problem

2023-10-19 03:18 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/executor/ObvDupeFilter.java
> +package zingg.common.core.executor;
So we are talking of two different things here. 
- A new possible phase for obviousDupes. If we do that, we need some kind of executor. 
- Breaking down the class 

The first one can always be defined later using the classes in second.

2023-10-19 03:20 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/executor/Matcher.java
>  			ZFrame<D, R, C> obvDupePairs = getObvDupePairs(blocked);
then we should override the new class in enterprise and introduce im and weave into the ent matcher. 

Obvious dupes logic should be encapsulated in its own package and classes.

2023-10-19 03:42 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/executor/Matcher.java
>  			ZFrame<D, R, C> obvDupePairs = getObvDupePairs(blocked);
I went back and checked the code. The following should not be part of the Matcher. 
`if (obvDupePairs != null) {
				long obvDupeCount = obvDupePairs.count();
				LOG.debug("obvDupePairs count " + obvDupeCount);
				if (obvDupeCount > 0) {
					blocks = removeObvDupesFromBlocks(blocks);
				}
			}
			`

The methods in the Matcher that you have defined can continue to call the obv dupes classes.

2023-10-19 04:48 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/executor/Matcher.java
>  			ZFrame<D, R, C> obvDupePairs = getObvDupePairs(blocked);
done in commit 70f1c33e, please review

2023-10-20 10:07 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/executor/ObvDupeFilter.java
> +	public C getObviousDupesFilter(ZFrame<D, R, C> df1, ZFrame<D, R, C> dfToJoin, String obviousDupeString, C extraAndCond) {
Done in commit c2ddce9d please review

2023-10-20 10:59 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/executor/ObvDupeFilter.java
> +package zingg.common.core.executor;
Refactor to two seperate classes in commit a3d77a68 and f3480e15

2023-10-20 11:11 UTC, vikasgupta78 commented
have completed all review comments of obv dupe filter in OSS
once you have merged than will do enterprise side of changes

2023-10-21 00:23 UTC, sonalgoyal requested changes

2023-10-21 00:23 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +    protected Context<S,D,R,C,T> context;
Do we need to pass Context or can we pass DSUtil ?

2023-10-21 00:23 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +    protected Context<S,D,R,C,T> context;
also see if S and T are needed for this class?

2023-10-21 00:23 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +		for (int i = 0; i < obviousDupes.length; i++) {
is tyhere a reason to loop through this one by one? I thought the filter would return the and, or conditions to join on completely?

2023-10-21 00:23 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +		if (reverseOBVDupeDFFilter != null) {
can our zframe methods take care of this so that we dont have to do null checks in main code?

2023-10-21 00:23 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeUtil.java
> +	public ZFrame<D,R,C> massageObvDupes(ZFrame<D,R,C> obvDupes) {
this belongs to the other class. It seems that the class names can be swapped - ObvDupeUtil can be renamed to ObviousDupeCondiiton or even ObvDupeFilter as it is only building the join/filter conditions.

2023-10-21 00:55 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +		for (int i = 0; i < obviousDupes.length; i++) {
We have to loop thru all the match conditions and within match conditions for every field name.

e.g "obviousDupes":[{   "matchCondition":[  { "fieldName":"fname"  },  { "fieldName":"stNo"  },  { "fieldName":"add1"  }   ]},{"matchCondition":[   {  "fieldName":"ssn"   }] }, {   "matchCondition":[{"fieldName":"fname" }, {"fieldName":"stNo" }, {"fieldName":"lname" }  ]} ],


so we loop thru to get 3 matchCondition and then within each matchCondition for each fieldName

forming something like 
(fname = z_fname and stNo = z_stNo and add1 = z_add1) OR 
(ssn = z_ssn) OR
(fname = z_fname and stNo = z_stNo and lname = z_lname)

2023-10-21 00:56 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeUtil.java
> +	public ZFrame<D,R,C> massageObvDupes(ZFrame<D,R,C> obvDupes) {
Please tell the names of both and I will do it.

2023-10-21 00:57 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +		if (reverseOBVDupeDFFilter != null) {
As Column can be used in various contexts => null check at all places where colum is used.

This is better

2023-10-21 01:23 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +    protected Context<S,D,R,C,T> context;
done in commit b29758c5 , please review

2023-10-21 01:37 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeUtil.java
> +	public ZFrame<D,R,C> massageObvDupes(ZFrame<D,R,C> obvDupes) {
method moved : commit 45e9205a

2023-10-21 07:06 UTC, sonalgoyal requested changes

2023-10-21 07:06 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeUtil.java
> +	public ZFrame<D,R,C> massageObvDupes(ZFrame<D,R,C> obvDupes) {
ObvDupeUtil is the class that applies the filters, adds and removes obv dupes 
ObvDupeCondition or ObvDupeFilter is the class that reads the args vaues and creates the conditions

2023-10-21 08:33 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeUtil.java
> +	public ZFrame<D,R,C> massageObvDupes(ZFrame<D,R,C> obvDupes) {
Renamed in commit 6db0092d , please review

2023-10-21 08:35 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +		if (reverseOBVDupeDFFilter != null) {
you are right as it will come in play only if obvious dupes there , removed redundant null in commit eb6b42f6

please review

2023-10-21 08:43 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +		for (int i = 0; i < obviousDupes.length; i++) {
This is query formation.

We don't actually use it exactly like this.

In case of getting obv dupes from blocked:

1. We use each and condition
2. union all the dfs got from above
3. do distinct
Directly doing OR was causing performance issues

For removing obv dupe from blocks
We first form a combined condition like above and than return a combined condition with NOT:
NOT (
(fname = z_fname and stNo = z_stNo and add1 = z_add1) OR
(ssn = z_ssn) OR
(fname = z_fname and stNo = z_stNo and lname = z_lname)
)

The way we make Column filter expression is independent of how we use it.

2023-10-21 08:45 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +		for (int i = 0; i < obviousDupes.length; i++) {
Basically we don;t use one final Column in end and we are flexible. You have asked similar question below, I hope this answers both

2023-10-21 08:52 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +		for (int i = 0; i < obviousDupes.length; i++) {
By keeping build of column of filter expression independent of how we use it we can use it as needed

2023-10-21 09:09 UTC, vikasgupta78 commented on common/core/src/main/java/zingg/common/core/obviousdupes/ObvDupeFilter.java
> +		for (int i = 0; i < obviousDupes.length; i++) {
also many of the methods are private only the public/protected can be used by outside code

2023-10-22 05:21 UTC, merged