added business exception class, issue #730
zinggAI/zingg pull request #731
Opened 2023-11-28 13:02 UTC by vikasgupta78

2023-11-28 16:28 UTC, sonalgoyal requested changes

2023-11-28 16:28 UTC, sonalgoyal commented on common/client/src/main/java/zingg/common/client/ZinggBusinessException.java
> +public class ZinggBusinessException extends Exception implements Serializable {
Do we need to extend Serializable given Exception already extends Serializable?

2023-11-28 16:28 UTC, sonalgoyal commented on common/client/src/main/java/zingg/common/client/ZinggBusinessException.java
> +	public ZinggBusinessException(String message, Throwable cause) {
should this be a throwable or an exception?

2023-11-28 16:41 UTC, vikasgupta78 commented on common/client/src/main/java/zingg/common/client/ZinggBusinessException.java
> +	public ZinggBusinessException(String message, Throwable cause) {
Throwable => Error as well => no graceful handling, no alternate route, no recovery scenarios

We want graceful handling so we need Exception as root not Throwable as it would never be Error

2023-11-28 16:47 UTC, vikasgupta78 commented on common/client/src/main/java/zingg/common/client/ZinggBusinessException.java
> +public class ZinggBusinessException extends Exception implements Serializable {
I did it because that's how it is in ZinggClientException

2023-11-28 16:51 UTC, sonalgoyal commented on common/client/src/main/java/zingg/common/client/ZinggBusinessException.java
> +	public ZinggBusinessException(String message, Throwable cause) {
Are you talking about line 17 here or the hierarchy?

2023-11-28 16:53 UTC, vikasgupta78 commented on common/client/src/main/java/zingg/common/client/ZinggBusinessException.java
> +	public ZinggBusinessException(String message, Throwable cause) {
hierarchy

2023-11-28 16:54 UTC, vikasgupta78 commented on common/client/src/main/java/zingg/common/client/ZinggBusinessException.java
> +	public ZinggBusinessException(String message, Throwable cause) {
The constructors are based on constructors of exception class

https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html

2023-11-28 16:57 UTC, sonalgoyal commented on common/client/src/main/java/zingg/common/client/ZinggBusinessException.java
> +	public ZinggBusinessException(String message, Throwable cause) {
ok, makes sense.

2023-11-28 16:59 UTC, vikasgupta78 commented on common/client/src/main/java/zingg/common/client/ZinggBusinessException.java
> +public class ZinggBusinessException extends Exception implements Serializable {
ya I can fix it. I thought it's done in ZinggClientException so that's how we should be doing it.

2023-11-28 17:03 UTC, sonalgoyal commented on common/client/src/main/java/zingg/common/client/ZinggBusinessException.java
> +public class ZinggBusinessException extends Exception implements Serializable {
no, feel free to point out issues, log bugs and fix whatever you can.

2023-11-29 05:16 UTC, vikasgupta78 commented on common/client/src/main/java/zingg/common/client/ZinggBusinessException.java
> +public class ZinggBusinessException extends Exception implements Serializable {
fixed in commit dc794dba

2023-11-30 06:01 UTC, merged