generate docs to show concise data if user so asks issue #723
zinggAI/zingg pull request #750
Opened 2023-12-27 14:15 UTC by vikasgupta78

generate docs to show concise data if user so asks issue #723

2023-12-27 16:07 UTC, sonalgoyal requested changes

2023-12-27 16:07 UTC, sonalgoyal commented on common/client/src/main/java/zingg/common/client/Arguments.java
> +	@JsonIgnore @Override
we should move this to a separate class. args dont need to know about match types

2023-12-27 16:35 UTC, vikasgupta78 commented on common/client/src/main/java/zingg/common/client/Arguments.java
> +	@JsonIgnore @Override
What would be a good place? I could have kept it in ModelDocumenter but keeping it at common place might be useful to others in future.

2023-12-27 16:39 UTC, sonalgoyal commented on common/client/src/main/java/zingg/common/client/Arguments.java
> +	@JsonIgnore @Override
yes it is likely useful to others. I think a FieldDefUtil may be ok for now.

2023-12-28 03:20 UTC, vikasgupta78 commented on common/client/src/main/java/zingg/common/client/Arguments.java
> +	@JsonIgnore @Override
Done in latest commit

2023-12-28 04:28 UTC, sonalgoyal commented on common/client/src/test/java/zingg/common/client/TestArguments.java
> +	protected FieldDefUtil fieldDefUtil = new FieldDefUtil();
These tests should be moved to a separate class for the util.

2023-12-28 04:29 UTC, sonalgoyal requested changes
Junit changes

2023-12-28 04:48 UTC, vikasgupta78 commented on common/client/src/test/java/zingg/common/client/TestArguments.java
> +	protected FieldDefUtil fieldDefUtil = new FieldDefUtil();
Done in latest commit

2023-12-28 05:42 UTC, merged