integration Junit for OSS
zinggAI/zingg pull request #778
Opened 2024-02-08 09:45 UTC by vikasgupta78

integration Junit for OSS

2024-02-17 11:08 UTC, sonalgoyal requested changes

2024-02-17 11:08 UTC, sonalgoyal commented on spark/spark-test/src/test/java/zingg/spark/core/executor/TestSparkExecutors.java
> +	public void testExecutors() throws ZinggClientException {
move this to the base class with S,D,R,C,T. Only getTrainingDataFinder etc should be overwritten to return concrete  class here

2024-02-17 11:08 UTC, sonalgoyal commented on common/common-test/pom.xml
> +			<groupId>zingg</groupId>
move tests to common test as discussed

2024-02-18 05:03 UTC, vikasgupta78 commented on common/common-test/src/test/java/zingg/common/core/executor/TrainerTester.java
> +	public void validateResults() {
https://github.com/zinggAI/zingg/issues/783 created

2024-02-18 05:04 UTC, vikasgupta78 commented on spark/spark-test/src/test/java/zingg/spark/core/executor/TestSparkExecutors.java
> +		args.getData()[0].setProp("location", testFile);
test data file not getting picked otherwise

2024-02-18 05:23 UTC, vikasgupta78 commented on common/common-test/src/test/java/zingg/common/core/executor/MatcherTester.java
> +	public abstract ZFrame<D, R, C> intersect(ZFrame<D, R, C> df1, ZFrame<D, R, C> df2);
done in commit 2c7f7447

2024-02-18 05:50 UTC, vikasgupta78 commented on spark/spark-test/src/test/java/zingg/spark/core/executor/TestSparkExecutors.java
> +	public void testExecutors() throws ZinggClientException {
Done in commit e18399e7

2024-02-18 05:51 UTC, vikasgupta78 commented on spark/spark-test/src/test/java/zingg/spark/core/executor/TestSparkExecutors.java
> +		stdf.init(args);
What would be the benefit in that? Moreover if something special needs to be done for an instance let it be done by concrete implementation

2024-02-18 06:13 UTC, sonalgoyal commented on spark/spark-test/src/test/java/zingg/spark/core/executor/TestSparkExecutors.java
> +		stdf.init(args);
That specific thing will anyways be done in the derived class. Setting up the test in one places ensures no code repetition and that all derived classes are executing the same tests, unless explicitly overridden

2024-02-18 08:11 UTC, vikasgupta78 commented on spark/spark-test/src/test/java/zingg/spark/core/executor/TestSparkExecutors.java
> +		stdf.init(args);
done in commit 6423793d

2024-02-18 11:53 UTC, vikasgupta78 commented on common/common-test/pom.xml
> +			<groupId>zingg</groupId>
done as part of commits 3a79946b , 2184a845 and 6b97885a

Please let me know if spark-test module also needs to be removed and tests moved to spark-core

2024-02-19 06:25 UTC, merged