Use environment variables in config files #60
zinggAI/zingg pull request #80
Opened 2021-12-17 06:32 UTC by navinrathore

Feature to allow user to pass environment variables for the Zingg configuration values #60

2021-12-17 09:57 UTC, sonalgoyal commented
Junis are meant to be atomic. So you build tests like testBooleanVar teststringVar testIntegerVar testDataPipeFormat testOutputPipexxxx testDataPipeArrayFormat etc etc...go as many cases as you can think of, and combinations testBooleanStringxxxxx 

the tests also need to address the specific issue - values of pipe properties

tests should also be there for malformed system var like $var or var$ - in case of boolean and int you should get exceptions, in other cases you should get exceptions again

and tests when something is referenced in json but not configured in env variable also need to be there.

2021-12-17 09:57 UTC, sonalgoyal commented
Also checkin comments need to be better - right now there are three commits with Use environment variables in config files. You can reference the issue in all commits, but the commit has to specify what is being changed too.

2021-12-20 16:50 UTC, navinrathore commented
The newly added testcases cover the above suggestions and other units/fragments of the  the code changes. I tried to avoid redundant and out of scope scenarios.

2021-12-21 08:42 UTC, navinrathore commented on client/src/main/java/zingg/client/Arguments.java
> +			throws ZinggClientException {
New Function added. 
Veryfing the code comments blocks added or not!

2021-12-21 09:51 UTC, sonalgoyal requested changes

2021-12-22 10:51 UTC, navinrathore commented on client/src/main/java/zingg/client/Arguments.java
> +			throws ZinggClientException {
Disregarded

2021-12-22 11:01 UTC, navinrathore commented on client/src/test/java/zingg/client/TestArguments.java
> -	public void testCreateArgsMissingDelimiterFile() {
done

2021-12-22 11:02 UTC, navinrathore commented on client/src/main/java/zingg/client/Arguments.java
> +			byte[] encoded = Files.readAllBytes(Paths.get(filePath));
It is a Java 11 function. No change is done.

2021-12-22 16:06 UTC, navinrathore commented on client/src/main/java/zingg/client/Arguments.java
> +				LOG.warn("The environment variable for {" + matcher.group(1) + "} is not set");
Added Exception.

2021-12-22 17:08 UTC, navinrathore commented
Made changes as per comments and the discussion

2021-12-23 04:24 UTC, sonalgoyal requested changes
Overall it is much better. few things 
- print at warn level which variables are getting substituted - only name, not value.
- test that $var without an end $ throws an exception
-  is there a way to ensure or test non .env file has no substitutions.

2021-12-23 05:46 UTC, navinrathore commented on client/src/test/java/zingg/client/TestArguments.java
> + 			System.out.println("Expected exception received due to blank value for an environment variable");
ok

2021-12-23 08:43 UTC, navinrathore commented
Made changes to add Logger in Tests; Added message for substituted environment variables as well.

2021-12-28 18:44 UTC, merged