Graceful message and exit for wrong value of phase
zinggAI/zingg pull request #84
Opened 2021-12-22 07:45 UTC by navinrathore

#81 wrong value of phase shows stack trace - should be handled gracefully

2021-12-22 08:13 UTC, sonalgoyal reviewed
Cant we just throw an exception and exit with the right message?

2021-12-22 08:20 UTC, sonalgoyal requested changes

2021-12-22 08:20 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Client.java
> +	public static final int EXIT_STATUS_ILLEGAL_CMD = 127;
this is not needed

2021-12-22 08:20 UTC, sonalgoyal commented on client/src/main/java/zingg/client/Client.java
> +			if (ZinggOptions.getByValue(phase) == null) {
throw exception with right message

2021-12-22 08:20 UTC, sonalgoyal commented on client/src/test/java/zingg/client/TestClient.java
> +			Process p = Runtime.getRuntime().exec(zinggInvalidPhaseCmd, null, new File(System.getenv("ZINGG_HOME")));
can we just call the client with the args instead of execing a new process here? and simply assert that an exception happens ?

2021-12-22 09:48 UTC, navinrathore commented on client/src/main/java/zingg/client/Client.java
> +	public static final int EXIT_STATUS_ILLEGAL_CMD = 127;
ok

2021-12-22 10:36 UTC, navinrathore commented on client/src/main/java/zingg/client/Client.java
> +			if (ZinggOptions.getByValue(phase) == null) {
This is the message as part of thrown exception
 Apologies for this message. Zingg has encountered an error. 'findTrainingDat' is not a valid phase. Valid phases are: train|match|trainMatch|findTrainingData|label|link

2021-12-22 17:51 UTC, navinrathore commented on client/src/test/java/zingg/client/TestClient.java
> +			Process p = Runtime.getRuntime().exec(zinggInvalidPhaseCmd, null, new File(System.getenv("ZINGG_HOME")));
testcases have been updated to test the new functionality that is refactored into ZinggOptions.verifyPhase(phase).
ZinggOptions has been chosen for it is the central place to maintain zingg options or phases.

2021-12-23 04:26 UTC, sonalgoyal approved these changes

2021-12-23 04:27 UTC, merged