Junit refactor
zinggAI/zingg pull request #852
Opened 2024-07-05 09:55 UTC by Nitish1814

2024-07-06 01:55 UTC, sonalgoyal requested changes
Early comments, will review in depth later in the day

2024-07-06 01:55 UTC, sonalgoyal commented on common/client/src/main/java/zingg/common/client/util/DFObjectUtil.java
> +public abstract class DFObjectUtil<S, D, R, C> {
Can you please break this up into an interface WithSession which has methods getSession and set session and then extend it? We will use the interface in other parts of the code as well later

2024-07-06 01:55 UTC, sonalgoyal commented on common/client/src/main/java/zingg/common/client/util/PojoToArrayConverter.java
> +    public static Object[] getObjectArray(Object person) throws IllegalAccessException {
Rename person to some sensible variable

2024-07-06 01:55 UTC, sonalgoyal commented on pom.xml
> -            <version>2.12.2</version>
Deps affect the enterprise version so unless you really need some extra feature from a new release, don’t change the versions. We do a deep migration exercise from time to time

2024-07-06 01:55 UTC, sonalgoyal commented on spark/client/pom.xml
> -		<fasterxml.jackson.databind.version>2.15.2</fasterxml.jackson.databind.version>
Especially Jackson versions affect a lot of things

2024-07-06 01:55 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +			JavaSparkContext.jarOfClass(TestZFrameBase.class);
Can you please check if jarOfclass method is needed ?

2024-07-06 01:55 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +			args = new Arguments();
Where is args needed?

2024-07-06 01:55 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +		StructType schemaOfSample = new StructType(new StructField[] {
The data has to be in common so it can be used to build other data frames

2024-07-06 01:55 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +		Dataset<Row> sample = spark.createDataFrame(Arrays.asList(
This has to be driven through the pojotoarrayconvertot and other common I told you defined

2024-07-06 09:15 UTC, sonalgoyal requested changes

2024-07-06 09:15 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +public abstract class TestZFrameBase<S, D, R, C, T> {
this class will go in common as we will use it in enterprise code for other types of dataframes and exeution engines, like Snowflake

2024-07-06 09:15 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +    public static class SchemaWithMixedDataType {
please make this a separate class in common test which will be used inother places. Rename to Person or relevant name

2024-07-06 09:15 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +    public static class SchemaZScore {
move all schema classes to common, remove Schema frm name and give descriptive name

2024-07-06 09:15 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +        public final Integer z_cluster;
z_cluster is a String. score is a double.

2024-07-06 09:15 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +        public final Integer z_zid;
z_zid is long

2024-07-06 09:15 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +        List<GenericRowWithSchema> pojoList = (List<GenericRowWithSchema>) zFrame.select(colName).collectAsList();
this should be List<R>

2024-07-06 09:20 UTC, sonalgoyal requested changes
Made some comments, please check

2024-07-06 09:42 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +        List<GenericRowWithSchema> pojoList = (List<GenericRowWithSchema>) zFrame.select(colName).collectAsList();
List<R>

2024-07-07 20:30 UTC, Nitish1814 commented on common/client/src/main/java/zingg/common/client/util/PojoToArrayConverter.java
> +    public static Object[] getObjectArray(Object person) throws IllegalAccessException {
renamed

2024-07-07 20:32 UTC, Nitish1814 commented on common/client/src/main/java/zingg/common/client/util/DFObjectUtil.java
> +public abstract class DFObjectUtil<S, D, R, C> {
code is taken from enterprise repo? needed to update?

2024-07-07 20:34 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +		Dataset<Row> sample = spark.createDataFrame(Arrays.asList(
its specific to sparkTest, other common data is driven through POJO classes

2024-07-07 20:34 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +        List<GenericRowWithSchema> pojoList = (List<GenericRowWithSchema>) zFrame.select(colName).collectAsList();
updated to List<R>

2024-07-08 04:53 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +			JavaSparkContext.jarOfClass(TestZFrameBase.class);
removed

2024-07-08 04:53 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +			args = new Arguments();
removed

2024-07-08 05:13 UTC, sonalgoyal requested changes
please adrdess remianing stuff like renaming, moving classes and deps etc

2024-07-08 07:57 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +    public static class SchemaWithMixedDataType {
done

2024-07-08 07:57 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +    public static class SchemaZScore {
done

2024-07-08 08:01 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +        public final Integer z_cluster;
done

2024-07-08 08:16 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestZFrameBase.java
> +        public final Integer z_zid;
done

2024-07-08 08:17 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +		StructType schemaOfSample = new StructType(new StructField[] {
done

2024-07-08 09:09 UTC, Nitish1814 commented on common/client/src/main/java/zingg/common/client/util/DFObjectUtil.java
> +public abstract class DFObjectUtil<S, D, R, C> {
done

2024-07-08 09:14 UTC, Nitish1814 commented on spark/client/pom.xml
> -		<fasterxml.jackson.databind.version>2.15.2</fasterxml.jackson.databind.version>
it's required in tests, what all needs to be test to validate this upgrade ? Trivial phases are working fine

2024-07-08 09:16 UTC, Nitish1814 commented on pom.xml
> -            <version>2.12.2</version>
it's required in tests, what all needs to be test to validate this upgrade ? Trivial phases are working fine

2024-07-08 10:17 UTC, Nitish1814 commented on pom.xml
> -            <version>2.12.2</version>
reverted back

2024-07-08 10:18 UTC, Nitish1814 commented on spark/client/pom.xml
> -		<fasterxml.jackson.databind.version>2.15.2</fasterxml.jackson.databind.version>
updated to 2.12.0 to be consistent with version in master pom

2024-07-08 16:19 UTC, sonalgoyal requested changes

2024-07-08 16:19 UTC, sonalgoyal commented on common/client/src/test/java/zingg/common/client/model/ClusterPairTwo.java
> +public class ClusterPairTwo {
ClusterPairOne and ClusterPairTwo can have same common class for cluster, score and source..

2024-07-08 16:19 UTC, sonalgoyal commented on common/client/src/test/java/zingg/common/client/model/ClusterSource.java
> +public class ClusterSource {
Call it InputWithZidAndSource

2024-07-08 16:19 UTC, sonalgoyal commented on common/client/src/test/java/zingg/common/client/model/ClusterPairOne.java
> +public class ClusterPairOne {
Call it PairPartOne and PairPartTwo

2024-07-08 16:19 UTC, sonalgoyal commented on spark/client/src/main/java/zingg/spark/client/util/SparkDFObjectUtil.java
> +    private final WithSession<SparkSession> withSparkSession;
move the attribute to base class

2024-07-08 16:19 UTC, sonalgoyal commented on common/client/src/main/java/zingg/common/client/util/WithSession.java
> +package zingg.common.client.util;
rename to IWithSession, and define concrete class WithSession<S> implemeting that. Use WithSession throughout. You would not need extra WithSparkSession

2024-07-08 16:19 UTC, sonalgoyal commented on spark/client/src/main/java/zingg/spark/client/util/SparkDFObjectUtil.java
> +    public SparkDFObjectUtil(WithSession<SparkSession> withSparkSession) {
you should not need these. move to base class

2024-07-08 16:19 UTC, sonalgoyal commented on spark/core/src/test/java/zingg/block/TestSparkBlock.java
> +    protected static void setUpSpark() {
there needs to be a commpn spark session weaving in all the spark junits - lets talk tomorrow on this

2024-07-08 16:19 UTC, sonalgoyal commented on common/core/src/test/java/zingg/data/Constant.java
> +public class Constant {
rename to TestData or TestDataGenerator or something more intuitive

2024-07-08 17:17 UTC, Nitish1814 commented on spark/core/src/test/java/zingg/block/TestSparkBlock.java
> +    protected static void setUpSpark() {
yeah, I had a note of this.. was thinking to add it last

2024-07-09 09:19 UTC, Nitish1814 commented on common/client/src/main/java/zingg/common/client/util/WithSession.java
> +package zingg.common.client.util;
done

2024-07-09 09:20 UTC, Nitish1814 commented on common/client/src/test/java/zingg/common/client/model/ClusterPairOne.java
> +public class ClusterPairOne {
done

2024-07-09 09:24 UTC, Nitish1814 commented on common/client/src/test/java/zingg/common/client/model/ClusterPairTwo.java
> +public class ClusterPairTwo {
done

2024-07-09 09:24 UTC, Nitish1814 commented on common/client/src/test/java/zingg/common/client/model/ClusterSource.java
> +public class ClusterSource {
done

2024-07-09 11:20 UTC, Nitish1814 commented on common/core/src/test/java/zingg/data/Constant.java
> +public class Constant {
done

2024-07-13 09:01 UTC, Nitish1814 commented on spark/client/src/main/java/zingg/spark/client/util/SparkDFObjectUtil.java
> +    private final WithSession<SparkSession> withSparkSession;
done

2024-07-13 09:08 UTC, Nitish1814 commented on spark/client/src/main/java/zingg/spark/client/util/SparkDFObjectUtil.java
> +    public SparkDFObjectUtil(WithSession<SparkSession> withSparkSession) {
done

2024-07-15 08:30 UTC, closed without merging