Test refactor
zinggAI/zingg pull request #864
Opened 2024-07-13 10:31 UTC by Nitish1814

Refactored ZFrame, Block and StopWord test classes

2024-07-15 08:17 UTC, sonalgoyal requested changes
1. Common naming for test data. We can define model package inside the package of the class we are testing. Can you come up with good naming here?
2. Assertions should not be repeated. Move to common utility and use throughout. 
3. Other changes requested at different places

2024-07-15 08:17 UTC, sonalgoyal commented on common/client/src/test/java/zingg/common/client/TestZFrameBase.java
> +    public void testCreateSparkDataFrameAndGetDF() throws Exception {
remove spark from name of method - like testCreateZFrameAndGetDF()

2024-07-15 08:17 UTC, sonalgoyal commented on common/client/src/test/java/zingg/common/client/TestZFrameBase.java
> +    public void testColumnsNamesandCount() throws Exception {
Check camel case

2024-07-15 08:17 UTC, sonalgoyal commented on common/client/src/test/java/zingg/common/client/TestZFrameBase.java
> +        List<C> columnList = (List<C>) Arrays.asList("recid", "surname", "postcode");
wont this give List<String> ?

2024-07-15 08:17 UTC, sonalgoyal commented on common/client/src/test/java/zingg/common/client/TestZFrameBase.java
> +        List<R> rows = zFrame.collectAsList();
can you build your assertions here and elsewhere as common methods which we can use elsewhere in the code - all our tests will have some semblence of getting some values or columns and asserting against values from a class/supplied values.  your other test methods also seem to have this same code

2024-07-15 08:17 UTC, sonalgoyal commented on common/client/src/test/java/zingg/common/client/model/PairPartOne.java
> +package zingg.common.client.model;
pairPartOne and PairPartTwo - possible to have common base class? that way if we change the field names later, we dont have to do it in two places.

2024-07-15 08:17 UTC, sonalgoyal commented on common/core/src/test/java/zingg/common/core/data/TestData.java
> +public class TestData {
rename to add the test class which is using this.

2024-07-15 08:17 UTC, sonalgoyal commented on common/core/src/test/java/zingg/common/core/model/EventCluster.java
> +public class EventCluster {
rename to EventPair

2024-07-15 08:17 UTC, sonalgoyal commented on common/core/src/test/java/zingg/common/core/model/EventCluster.java
> +public class EventCluster {
use base class EventBase and exetnd in both Event and EventPair?

2024-07-15 08:17 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +    public static IArguments args;
why do oyu need args here?

2024-07-15 08:17 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +    public static SparkSession spark;
these should be part of the base class - when you add the concrete class here, they will automatically have the right strucgture.

2024-08-09 07:18 UTC, sonalgoyal commented on spark/core/src/test/java/zingg/common/core/block/TestSparkBlock.java
> +        try {
we have a generic sparkbasetester which sets the session, we should use that

2024-08-09 07:19 UTC, sonalgoyal requested changes
please check comments

2024-08-09 07:19 UTC, sonalgoyal commented on spark/core/src/test/java/zingg/common/core/util/SparkStopWordRemoverUtility.java
> +        //add second stopWordRemover
setting up the stop word removers should be in generic base class

2024-08-11 14:22 UTC, Nitish1814 commented on common/client/pom.xml
> +	<build>
done

2024-08-11 14:28 UTC, Nitish1814 commented on common/client/src/test/java/zingg/common/client/model/PairPartOne.java
> +package zingg.common.client.model;
the downstream task which uses this Pair Object will try to create row with superclass properties(Pair) and then child class properties(pairPartOne). which will create consistency issue for now

2024-08-11 14:33 UTC, Nitish1814 commented on common/core/src/test/java/zingg/common/core/model/EventCluster.java
> +public class EventCluster {
done

2024-08-11 19:28 UTC, Nitish1814 commented on spark/core/src/test/java/zingg/common/core/block/TestSparkBlock.java
> +        try {
done

2024-08-11 19:41 UTC, Nitish1814 commented on spark/core/src/test/java/zingg/common/core/util/SparkStopWordRemoverUtility.java
> +        //add second stopWordRemover
getStopWordRemovers() will provide different kind and number of stopword removers based on Spark or Snow implementation. IStopWordsRemoverutility interface only exposes getStopWordRemovers() method

2024-08-12 06:11 UTC, Nitish1814 commented on common/client/src/test/java/zingg/common/client/TestZFrameBase.java
> +    public void testCreateSparkDataFrameAndGetDF() throws Exception {
done

2024-08-12 06:11 UTC, Nitish1814 commented on common/client/src/test/java/zingg/common/client/TestZFrameBase.java
> +    public void testColumnsNamesandCount() throws Exception {
done

2024-08-12 06:18 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +    public static IArguments args;
removed

2024-08-12 08:30 UTC, sonalgoyal requested changes

2024-08-12 08:30 UTC, sonalgoyal commented on spark/client/pom.xml
> +		<fasterxml.jackson.version>2.12.0</fasterxml.jackson.version>
why are we changing this?

2024-08-12 08:30 UTC, sonalgoyal commented on common/client/src/test/java/zingg/common/client/data/TestData.java
> +        return new ArrayList<>();
No empty diamond operators

2024-08-12 08:30 UTC, sonalgoyal commented on common/client/src/test/java/zingg/common/client/util/TestStringRedactor.java
> -import java.util.Arrays;
please avoid changes to classes you are not touching

2024-08-12 08:30 UTC, sonalgoyal commented on common/core/src/test/java/zingg/common/core/data/EventTestData.java
> +        List<Event> sample = new ArrayList<>();
please give class when you instantiate

2024-08-12 08:30 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +    protected static void setUpSpark() {
we need to use the common testsparkbase or move the enterprise SparkSession weaving here which can inject the session. session for tests should not get created in multiple places

2024-08-12 08:30 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +        StructType schemaOfSample = new StructType(new StructField[]{
these should be coming from the base test class. Why are they here?

2024-08-12 08:30 UTC, sonalgoyal commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +    protected void assertTrueCheckingExceptOutput(ZFrame<Dataset<Row>, Row, Column> sf1, ZFrame<Dataset<Row>, Row, Column> sf2, String message) {
this should be part of the base test class so it can be used in enterprise and SnowFrame directly

2024-08-12 08:30 UTC, sonalgoyal commented on spark/core/src/test/java/zingg/common/core/block/TestSparkBlock.java
> +        try {
Sorry I dont see you using the common base class which sets up Spark session. Please move it from enterprise and use it here.

2024-08-12 08:30 UTC, sonalgoyal commented on spark/core/src/test/java/zingg/common/core/util/SparkStopWordRemoverUtility.java
> +        sparkStopWordsRemovers.add(new SparkStopWordsRemover(context,stmtArgs));
only this should be done here. the rest of the code is common and should move to an abstract class impl of IStopWordRemoverUtility

2024-08-12 09:33 UTC, Nitish1814 commented on spark/core/src/test/java/zingg/common/core/util/SparkStopWordRemoverUtility.java
> +        sparkStopWordsRemovers.add(new SparkStopWordsRemover(context,stmtArgs));
done

2024-08-12 10:25 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +    protected static void setUpSpark() {
done

2024-08-12 10:27 UTC, Nitish1814 commented on common/client/src/test/java/zingg/common/client/util/TestStringRedactor.java
> -import java.util.Arrays;
only removed unused import

2024-08-12 10:32 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +        StructType schemaOfSample = new StructType(new StructField[]{
refactored

2024-08-12 10:32 UTC, Nitish1814 commented on spark/client/src/test/java/zingg/client/TestSparkFrame.java
> +    protected void assertTrueCheckingExceptOutput(ZFrame<Dataset<Row>, Row, Column> sf1, ZFrame<Dataset<Row>, Row, Column> sf2, String message) {
refactored

2024-08-12 10:34 UTC, Nitish1814 commented on common/core/src/test/java/zingg/common/core/data/EventTestData.java
> +        List<Event> sample = new ArrayList<>();
It is a class static property for test purpose, there's no reason to make it instance dependent

2024-08-14 10:00 UTC, merged