tests for compound phases
zinggAI/zingg pull request #903
Opened 2024-10-02 17:22 UTC by sania-16

2024-10-02 17:24 UTC, sania-16 commented on spark/core/src/test/java/zingg/spark/core/executor/TestSparkExecutors.java
> +	protected SparkFindAndLabeller getFindAndLabeller() throws ZinggClientException {
getting this error here - The method getFindAndLabeller() of type TestSparkExecutors must override or implement a supertype methodJava(67109498)

not sure how to resolve it

2024-10-02 17:24 UTC, sania-16 commented on spark/core/src/test/java/zingg/spark/core/executor/TestSparkExecutors.java
> +	protected SparkTrainMatcher getTrainMatcher() throws ZinggClientException {
getting this error here - The method getFindAndLabeller() of type TestSparkExecutors must override or implement a supertype methodJava(67109498)

not sure how to resolve it

2024-10-02 17:25 UTC, sania-16 commented on common/core/src/test/java/zingg/common/core/executor/TestExecutorsCompoundPhase.java
> +	protected abstract TrainMatchTester<S, D, R, C, T> getTrainMatchTester(TrainMatcher<S, D, R, C, T> trainMatch);
what exactly is the function of having two testers?

followed the same pattern as in TestExecutorsGeneric

2024-10-02 17:26 UTC, sania-16 commented
@sonalgoyal 
please review comments added

2024-10-03 06:45 UTC, sonalgoyal requested changes
check this

2024-10-03 06:45 UTC, sonalgoyal commented on common/core/src/test/java/zingg/common/core/executor/TestExecutorsCompoundPhase.java
> +	protected abstract TrainMatchTester<S, D, R, C, T> getTrainMatchTester(TrainMatcher<S, D, R, C, T> trainMatch);
you have to run findandlabeller two times and then validate.

2024-10-03 06:45 UTC, sonalgoyal commented on common/core/src/test/java/zingg/common/core/executor/TrainMatchTester.java
> +	protected void assessAccuracy() throws ZinggClientException {
this code is the same as match tester. they should be in one place - like some util function and called through that. or you could just use the MatchTester directly.

2024-10-03 06:45 UTC, sonalgoyal commented on spark/core/src/test/java/zingg/spark/core/executor/SparkTrainMatchTester.java
> +	public void validateResults() throws ZinggClientException {
dont duplicate code. use the same tester

2024-10-04 05:36 UTC, sania-16 commented
@sonalgoyal 
not sure about the structuring of TestSparkExecutors and TestSparkExecutorsCompound

2024-10-04 14:20 UTC, sania-16 commented on common/core/src/test/java/zingg/common/core/executor/ExecutorValidator.java
> +		this.validator = validator;
function name or argument being passed @sonalgoyal ?

2024-10-05 07:38 UTC, sania-16 commented on common/core/src/test/java/zingg/common/core/executor/LabellerValidator.java
> +		ZFrame<D, R, C> dfMarked = validator.getContext().getPipeUtil().
as we are extending ExecutorValidator - how can we use executor?
either we extend ExecutorTester and use executor here as instance in both constructor and validateResults else have to use validator

2024-10-05 07:40 UTC, sania-16 commented on common/core/src/test/java/zingg/common/core/executor/FindAndLabelValidator.java
> +    public void validateResults() throws ZinggClientException {
![Screenshot 2024-10-05 at 1 09 36 PM](https://github.com/user-attachments/assets/23865474-0f53-4597-9046-df91f1115742)

we are creating instances of tdfvalidator and labeller validator and using them - is the implementation wrong?

2024-10-05 07:42 UTC, sania-16 commented on common/core/src/test/java/zingg/common/core/executor/LinkerValidator.java
> +		ZFrame<D, R, C> df2 = getOutputData().distinct().withColumn("z_zsource", "test2");
yes - don't need - removed

2024-10-05 07:43 UTC, sania-16 commented on common/core/src/test/java/zingg/common/core/executor/LinkerValidator.java
> +		C col2 = df2.col(colName+"1");
we can directly call the MatcherValidator one?

2024-10-05 13:19 UTC, sania-16 commented on common/core/src/test/java/zingg/common/core/executor/ExecutorValidator.java
> +		this.validator = validator;
have renamed to executorObj - arguments and instance

2024-10-05 13:26 UTC, sania-16 commented on spark/core/src/test/java/zingg/spark/core/executor/TestSparkExecutors.java
>  	@Override
how to define setupArgs() for linker because we have to pass two data sources along with a different config?

2024-10-16 06:37 UTC, merged