blocking tree changes
zinggAI/zingg pull request #924
Opened 2024-10-21 19:34 UTC by Nitish1814

blocking tree changes!

-> added path set in isHashFunctionUsed() to avoid recursive call at each node

2024-10-21 19:38 UTC, Nitish1814 commented on common/core/src/main/java/zingg/common/core/block/blockingTree/DefaultBockingTreeBuilder.java
> +package zingg.common.core.block.blockingTree;
camel case used

2024-10-21 19:38 UTC, Nitish1814 commented on common/core/src/main/java/zingg/common/core/block/blockingTree/IBlockingTreeBuilder.java
> +package zingg.common.core.block.blockingTree;
camel case used

2024-10-21 19:39 UTC, Nitish1814 commented on common/core/src/main/java/zingg/common/core/block/blockingTree/OptimizedBlockingTreeBuilder.java
> +package zingg.common.core.block.blockingTree;
camel case used

2024-10-21 19:40 UTC, Nitish1814 commented on spark/core/src/main/java/zingg/spark/core/block/blockingTree/SparkDefaultBlockingTreeBuilder.java
> +package zingg.spark.core.block.blockingTree;
camel case used

2024-10-21 19:40 UTC, Nitish1814 commented on spark/core/src/main/java/zingg/spark/core/block/blockingTree/SparkOptimizedBlockingTreeBuilder.java
> +package zingg.spark.core.block.blockingTree;
camel case used

2024-10-21 19:43 UTC, Nitish1814 commented on spark/core/src/test/java/zingg/spark/core/block/TestBlockingTreeUtil.java
> +        FileReader filereader = new FileReader(TEST_DATA_BASE_LOCATION + "test20k.csv");
Needed to give fileReader object to csvReader

2024-10-21 19:46 UTC, Nitish1814 commented on common/core/src/main/java/zingg/common/core/block/blockingTree/OptimizedBlockingTreeBuilder.java
> +    public static final Log LOG = LogFactory.getLog(OptimizedBlockingTreeBuilder.class);
followed consistent declaration. will fix part of different issue

2024-10-21 19:46 UTC, Nitish1814 commented on common/core/src/main/java/zingg/common/core/block/blockingTree/OptimizedBlockingTreeBuilder.java
> +        Tree<Canopy<R>> blockingTree = dfsToGetBlockingTree(tree, parent, node, fieldsOfInterest, cblock.getHashFunctionsInCurrentNodePath(), cblock);
for clarity purpose

2024-10-21 19:48 UTC, Nitish1814 commented on common/core/src/main/java/zingg/common/core/block/blockingTree/OptimizedBlockingTreeBuilder.java
> +                LOG.warn("Ran out of training at size " + size + " for node " + node);
controller by log level

2024-12-30 11:26 UTC, sonalgoyal requested changes
pls check

2025-01-01 15:58 UTC, Nitish1814 commented on common/core/src/test/java/zingg/common/core/block/data/DataReader.java
> +public interface DataReader {
done

2025-01-01 15:58 UTC, Nitish1814 commented on common/core/src/test/java/zingg/common/core/block/data/ICsvReader.java
> +public interface ICsvReader extends DataReader {
done

2025-01-01 15:58 UTC, Nitish1814 commented on common/core/src/main/java/zingg/common/core/block/CacheBasedHashFunctionUtility.java
> +        this.hashFunctionsInCurrentNodePath = new HashSet<>();
done

2025-01-03 07:47 UTC, merged