Sim and Hash functions for Boolean Datatype
zinggAI/zingg pull request #925
Opened 2024-10-22 08:00 UTC by sania-16

have added similarity and hash functions issue #921 
please review @sonalgoyal 
need to work on integrating and testing them

2024-10-23 06:53 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/hash/HashFnBoolean.java
> +        return Boolean.hashCode(field); // 1231 for true and 1237 for false
no need for this hash fucntion

2024-10-23 06:54 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/similarity/function/BooleanSimilarityFunction.java
> +		if (first == null && second == null) return 1d;
there is a common generic class similarity function which has all this logic defined. you can use it directly.

2024-10-23 07:00 UTC, sania-16 commented on common/core/src/main/java/zingg/common/core/hash/HashFnBoolean.java
> +        return Boolean.hashCode(field); // 1231 for true and 1237 for false
will remove this class completely

2024-10-23 07:00 UTC, sania-16 commented on common/core/src/main/java/zingg/common/core/similarity/function/BooleanSimilarityFunction.java
> +		if (first == null && second == null) return 1d;
will integrate it inside the call function

2024-10-23 07:01 UTC, sania-16 commented
sim and hash functions need to be added as well to the registries - hashfunctionregistry and featurefactory

2024-11-06 05:24 UTC, sonalgoyal requested changes
see comments.

also add BooleanFeature to the SparkFeatureFactory

2024-11-06 05:24 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/feature/BooleanFeature.java
> +        if (f.getMatchType().contains(MatchType.FUZZY)) {
dont think there is a use for fuzzy in boolean. please remove

2024-11-06 05:24 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/similarity/function/BooleanSimilarityFunction.java
> +	public static final Log LOG = LogFactory.getLog(BooleanSimilarityFunction.class);
you dont need a class for this type. see how we are doing it for dates in the DateFeature. addSimFunction(new SimilarityFunctionExact<Date>("DateSimilarityFunctionExact"));

2024-11-06 05:48 UTC, sania-16 commented on common/core/src/main/java/zingg/common/core/similarity/function/BooleanSimilarityFunction.java
> +	public static final Log LOG = LogFactory.getLog(BooleanSimilarityFunction.class);
@sonalgoyal 
For DateFeature, we do have DateSimilarityFunction.java defined
So do we need this class?

2024-11-07 07:15 UTC, merged