Vertical col support
zinggAI/zingg pull request #945
Opened 2024-11-08 11:54 UTC by Nitish1814

2024-11-12 16:36 UTC, sonalgoyal requested changes

2024-11-12 16:36 UTC, sonalgoyal commented on common/client/src/main/java/zingg/common/client/util/verticalDisplay/VerticalDisplayUtility.java
> +        List<Pair<String, String>> comparison_pairs = new ArrayList<>();
you dont need an intermediary structure here. collectAsList would give you the List<Row> rows and you can iterate over the columns to build VerticalDisplayModel(df.getAsString(rows[0], column, df.getAsString(rows[1], column)

2024-11-12 16:36 UTC, sonalgoyal commented on common/core/src/test/java/zingg/common/core/util/TestVerticalDisplayUtility.java
> +    public void testWithoutNulls() throws Exception, ZinggClientException {
can you also try with an empty dataframe?

2024-11-13 06:45 UTC, Nitish1814 commented on common/core/src/test/java/zingg/common/core/util/TestVerticalDisplayUtility.java
> +    public void testWithoutNulls() throws Exception, ZinggClientException {
done

2024-11-13 06:50 UTC, Nitish1814 commented on common/client/src/main/java/zingg/common/client/util/verticalDisplay/VerticalDisplayModel.java
> +package zingg.common.client.util.verticalDisplay;
done

2024-11-13 07:45 UTC, merged