Laod test suite
zinggAI/zingg pull request #952
Opened 2024-11-12 13:50 UTC by Nitish1814

changes
1- added time to report
2- report will be created under ./perfTestReport folder
3- every report will overwrite previous report

2024-11-12 14:49 UTC, sonalgoyal requested changes
report name has date which means it is not getting overwritten?

see other comments.

2024-11-12 14:49 UTC, sonalgoyal commented on .github/workflows/load-test.yml
> +  push:
why on push?

2024-11-12 14:49 UTC, sonalgoyal commented on common/core/src/main/java/zingg/common/core/block/Canopy.java
> +	private static final long serialVersionUID = -229533781044789499L;
why are we adding it here? and this value in any case is not making sense.

2024-11-12 14:49 UTC, sonalgoyal commented on perf_test_input.py
>  config_65 = "examples/febrl120k/config.json"
rename to febrl, febrl120k, ncVoter5m

2024-11-14 13:36 UTC, Nitish1814 commented on perf_test_input.py
>  config_65 = "examples/febrl120k/config.json"
done

2024-11-15 04:28 UTC, merged