logging location of the file being read #83
zinggAI/zingg pull request #97
Opened 2021-12-29 12:59 UTC by navinrathore

The output location would look like : (2nd line)
2021-12-29 18:18:22,739 [main] WARN  zingg.util.PipeUtil - Reading input PARQUET
**2021-12-29 18:18:22,740 [main] WARN  zingg.util.PipeUtil - Reading location: models/1000/trainingData//unmarked/**

If entire pipe info is printed, for some scenario other information also get printed. So this option dropped
e.g.
Reading input Pipe [name=null, format=PARQUET, preprocessors=null, props={location=models/1000/trainingData//unmarked/}, schema=null]
Reading input Pipe [name=customers, format=SNOWFLAKE, preprocessors=null, props={sfUrl=tsa87485.snowflakecomputing.com, sfUser=sonalgoyal, sfPassword=ZZZZZ, sfDatabase=DEMO_DB, sfSchema=PUBLIC, sfWarehouse=COMPUTE_WH, dbtable=CUSTOMERS}, schema=null]

2021-12-29 13:46 UTC, sonalgoyal commented
We need the second option.

2021-12-29 13:49 UTC, sonalgoyal requested changes
Need to print entire pipe. It will become an issue for others sensitive information like passwords etc, log an issue for that separately

2021-12-29 14:34 UTC, navinrathore commented
There are two place where the entire pipe information can be logged.
a) inside read(), same place as done in current commit. It is a new statement
b) update info in existing logging statement but a bit higher place in getReader() that is invariably executed before reading.
 PipeUtil.java
58  LOG.warn("Reading input " + p.getFormat().type());

Please suggest.

2021-12-29 15:35 UTC, navinrathore commented
> There are two place where the entire pipe information can be logged. a) inside read(), same place as done in current commit. It is a new statement b) update info in existing logging statement but a bit higher place in getReader() that is invariably executed before reading. PipeUtil.java 58 LOG.warn("Reading input " + p.getFormat().type());
> 
> Please suggest.

Option A has been chosen as advised.

2021-12-29 15:49 UTC, sonalgoyal requested changes
seems there is some confusion,. We need to print the entire pipe not just location.

2021-12-29 15:49 UTC, sonalgoyal commented
> Need to print entire pipe. It will become an issue for others sensitive information like passwords etc, log an issue for that separately

this with the right read method

2021-12-29 15:53 UTC, sonalgoyal requested changes
https://github.com/zinggAI/zingg/pull/97#issuecomment-1002658799

2021-12-30 08:30 UTC, navinrathore commented
Logging of pipe information is done in all cases

2021-12-30 08:31 UTC, merged